/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import code.AdminLogin;
import code.Finance;
import code.admissionChallan;
import javax.swing.JPanel;

/**
 *
 * @author Muhammad Faraz
 */
public class adchalllllanDesire extends javax.swing.JPanel {

    /**
     * Creates new form adchalllllanDesire
     */
    JPanel childPanel;
    int mon=0;
        int ye=0;
        admissionChallan admis=new admissionChallan();
    AdminLogin ADMIN=new AdminLogin();

    public adchalllllanDesire() {
        initComponents();
     
         admis.setChallan2(name, name1, name2, regNo, regNo1, regNo3, classes, classes1, classes2, fees, fees1, fees2, regFees, jLabel20, jLabel19, total, total1, total2, afterFees, afterFees1, afterFees2,jLabel36, p, p1, ins, ins1, jLabel38, in, in3, in1, instal, instal1, instal2, zz, zz1, zz2, xx, xx1, xx2,due,due1,jLabel51,month,month2,month3,Date,date1,date2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        printpicture = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        mobno = new javax.swing.JLabel();
        bank = new javax.swing.JLabel();
        challanpayable = new javax.swing.JLabel();
        acountnu = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        classes = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        regNo = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        month = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        classes3 = new javax.swing.JLabel();
        classes4 = new javax.swing.JLabel();
        classes5 = new javax.swing.JLabel();
        instal = new javax.swing.JLabel();
        xx = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        in3 = new javax.swing.JLabel();
        fees = new javax.swing.JLabel();
        regFees = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        zz = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jPanel34 = new javax.swing.JPanel();
        regNo1 = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        month2 = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        classes1 = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jPanel36 = new javax.swing.JPanel();
        jPanel37 = new javax.swing.JPanel();
        jPanel38 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jPanel39 = new javax.swing.JPanel();
        jPanel40 = new javax.swing.JPanel();
        jPanel41 = new javax.swing.JPanel();
        jPanel42 = new javax.swing.JPanel();
        jPanel43 = new javax.swing.JPanel();
        jPanel44 = new javax.swing.JPanel();
        classes6 = new javax.swing.JLabel();
        classes7 = new javax.swing.JLabel();
        classes8 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        p = new javax.swing.JLabel();
        ins = new javax.swing.JLabel();
        in = new javax.swing.JLabel();
        fees1 = new javax.swing.JLabel();
        instal1 = new javax.swing.JLabel();
        zz1 = new javax.swing.JLabel();
        xx1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel45 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        pay = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel46 = new javax.swing.JPanel();
        bankstamp = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        l = new javax.swing.JLabel();
        g = new javax.swing.JLabel();
        jPanel53 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jPanel54 = new javax.swing.JPanel();
        jPanel55 = new javax.swing.JPanel();
        jPanel56 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jPanel57 = new javax.swing.JPanel();
        jPanel58 = new javax.swing.JPanel();
        jPanel59 = new javax.swing.JPanel();
        jPanel60 = new javax.swing.JPanel();
        jPanel61 = new javax.swing.JPanel();
        jPanel62 = new javax.swing.JPanel();
        classes9 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        classes10 = new javax.swing.JLabel();
        classes11 = new javax.swing.JLabel();
        fees2 = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();
        in1 = new javax.swing.JLabel();
        ins1 = new javax.swing.JLabel();
        instal2 = new javax.swing.JLabel();
        zz2 = new javax.swing.JLabel();
        xx2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        bank2 = new javax.swing.JLabel();
        jPanel47 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel48 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jPanel50 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jPanel51 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jPanel52 = new javax.swing.JPanel();
        regNo3 = new javax.swing.JLabel();
        date2 = new javax.swing.JLabel();
        month3 = new javax.swing.JLabel();
        name2 = new javax.swing.JLabel();
        classes2 = new javax.swing.JLabel();
        jPanel49 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        acountnu2 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        challanpayable2 = new javax.swing.JLabel();
        mobno2 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jPanel63 = new javax.swing.JPanel();
        jPanel64 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jPanel65 = new javax.swing.JPanel();
        acountnu3 = new javax.swing.JLabel();
        challanpayable3 = new javax.swing.JLabel();
        bank3 = new javax.swing.JLabel();
        mobno3 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        afterFees = new javax.swing.JLabel();
        afterFees1 = new javax.swing.JLabel();
        afterFees2 = new javax.swing.JLabel();
        total1 = new javax.swing.JLabel();
        due = new javax.swing.JLabel();
        total2 = new javax.swing.JLabel();
        due1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1082, 779));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(834, 857));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/icons8-back-48.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setText("ADMISSION FEE CHALLAN");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 14, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(51, 153, 255));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel6MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel6MouseReleased(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/icons8-send-to-printer-40.png"))); // NOI18N
        jLabel26.setText("PRINT");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        printpicture.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(1080, 630));
        jPanel4.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setPreferredSize(new java.awt.Dimension(3, 147));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 764, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5);
        jPanel5.setBounds(712, 674, 0, 764);

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setPreferredSize(new java.awt.Dimension(2, 100));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel7);
        jPanel7.setBounds(270, 0, 2, 680);

        mobno.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        mobno.setText("              Mob: 0333-012371, 0334-0123771");
        jPanel4.add(mobno);
        mobno.setBounds(0, 30, 240, 20);

        bank.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        bank.setText("  BANK AL HABIB LIMITED, FORT CORNER BRANCH");
        jPanel4.add(bank);
        bank.setBounds(0, 50, 260, 16);

        challanpayable.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        challanpayable.setText("   (Challan payable at any branch of Bank Al Habib)");
        jPanel4.add(challanpayable);
        challanpayable.setBounds(0, 70, 290, 10);

        acountnu.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        acountnu.setText(" 1109-0981-008405-01-7");
        jPanel4.add(acountnu);
        acountnu.setBounds(0, 80, 270, 20);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(null);

        classes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        classes.setText("Reg No.");
        jPanel8.add(classes);
        classes.setBounds(100, 70, 160, 20);

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));
        jPanel9.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel9);
        jPanel9.setBounds(50, 20, 100, 2);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("Date:");
        jPanel8.add(jLabel4);
        jLabel4.setBounds(150, 0, 32, 17);

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));
        jPanel11.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel11);
        jPanel11.setBounds(190, 20, 100, 2);

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setText("Fees for the Month of");
        jPanel8.add(jLabel7);
        jLabel7.setBounds(0, 30, 121, 17);

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));
        jPanel10.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 195, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel10);
        jPanel10.setBounds(130, 40, 195, 2);

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel8.setText("Name:");
        jPanel8.add(jLabel8);
        jLabel8.setBounds(0, 50, 38, 17);

        jPanel12.setBackground(new java.awt.Color(0, 0, 0));
        jPanel12.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel12);
        jPanel12.setBounds(50, 70, 290, 2);

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel9.setText("Class/Section:");
        jPanel8.add(jLabel9);
        jLabel9.setBounds(0, 80, 77, 17);

        jPanel13.setBackground(new java.awt.Color(0, 0, 0));
        jPanel13.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel13);
        jPanel13.setBounds(80, 90, 276, 2);

        jLabel21.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel21.setText("Reg No.");
        jPanel8.add(jLabel21);
        jLabel21.setBounds(0, 0, 45, 17);

        regNo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        regNo.setText("Reg No.");
        jPanel8.add(regNo);
        regNo.setBounds(60, 0, 90, 17);

        Date.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Date.setText("Reg No.");
        jPanel8.add(Date);
        Date.setBounds(190, 0, 80, 15);

        month.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        month.setText("Reg No.");
        month.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel8.add(month);
        month.setBounds(130, 20, 140, 20);

        name.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        name.setText("Reg No.");
        name.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel8.add(name);
        name.setBounds(60, 48, 200, 20);

        jPanel4.add(jPanel8);
        jPanel8.setBounds(0, 100, 270, 100);

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel10.setText("Amount");
        jPanel17.add(jLabel10);
        jLabel10.setBounds(200, 10, 45, 17);

        jPanel14.setBackground(new java.awt.Color(0, 0, 0));
        jPanel14.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel17.add(jPanel14);
        jPanel14.setBounds(0, 0, 390, 2);

        jPanel15.setBackground(new java.awt.Color(0, 0, 0));
        jPanel15.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel17.add(jPanel15);
        jPanel15.setBounds(0, 210, 390, 2);

        jPanel16.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        jPanel17.add(jPanel16);
        jPanel16.setBounds(190, 0, 2, 210);

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel11.setText("Description");
        jPanel17.add(jLabel11);
        jLabel11.setBounds(10, 10, 64, 17);

        jPanel18.setBackground(new java.awt.Color(0, 0, 0));
        jPanel18.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel17.add(jPanel18);
        jPanel18.setBounds(0, 30, 390, 2);

        jPanel19.setBackground(new java.awt.Color(0, 0, 0));
        jPanel19.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel17.add(jPanel19);
        jPanel19.setBounds(0, 60, 390, 2);

        jPanel20.setBackground(new java.awt.Color(0, 0, 0));
        jPanel20.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel17.add(jPanel20);
        jPanel20.setBounds(0, 90, 390, 2);

        jPanel21.setBackground(new java.awt.Color(0, 0, 0));
        jPanel21.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel17.add(jPanel21);
        jPanel21.setBounds(0, 120, 390, 2);

        jPanel22.setBackground(new java.awt.Color(0, 0, 0));
        jPanel22.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel17.add(jPanel22);
        jPanel22.setBounds(0, 150, 390, 2);

        jPanel23.setBackground(new java.awt.Color(0, 0, 0));
        jPanel23.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel17.add(jPanel23);
        jPanel23.setBounds(0, 180, 390, 2);

        classes3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        classes3.setText("Monthly Fee");
        jPanel17.add(classes3);
        classes3.setBounds(0, 40, 180, 17);

        classes4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        classes4.setText("Registration Fee");
        jPanel17.add(classes4);
        classes4.setBounds(0, 70, 180, 17);

        classes5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        classes5.setText("Discount");
        jPanel17.add(classes5);
        classes5.setBounds(10, 190, 180, 17);

        instal.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        instal.setText("jLabel33");
        jPanel17.add(instal);
        instal.setBounds(10, 100, 110, 17);

        xx.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        xx.setText("jLabel44");
        jPanel17.add(xx);
        xx.setBounds(10, 130, 130, 17);

        jLabel36.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel36.setText("jLabel36");
        jPanel17.add(jLabel36);
        jLabel36.setBounds(200, 100, 70, 17);

        jLabel38.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel38.setText("jLabel38");
        jPanel17.add(jLabel38);
        jLabel38.setBounds(200, 160, 70, 17);

        jLabel62.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel62.setText("jLabel55");
        jPanel17.add(jLabel62);
        jLabel62.setBounds(210, 290, 70, 20);

        in3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        in3.setText("jLabel1");
        jPanel17.add(in3);
        in3.setBounds(200, 130, 50, 20);

        fees.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        fees.setText("Reg No.");
        jPanel17.add(fees);
        fees.setBounds(200, 40, 80, 17);

        regFees.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        regFees.setText("Reg No.");
        jPanel17.add(regFees);
        regFees.setBounds(200, 70, 80, 17);

        jTextField1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel17.add(jTextField1);
        jTextField1.setBounds(209, 180, 60, 30);

        zz.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        zz.setText("jLabel37");
        jPanel17.add(zz);
        zz.setBounds(10, 160, 140, 17);

        jPanel4.add(jPanel17);
        jPanel17.setBounds(0, 206, 270, 220);

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel12.setText("Payment before Due Date");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel4.add(jLabel12);
        jLabel12.setBounds(0, 420, 147, 20);

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel13.setText(" Due Date");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(0, 450, 60, 17);

        jPanel24.setBackground(new java.awt.Color(0, 0, 0));
        jPanel24.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 136, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel24);
        jPanel24.setBounds(100, 470, 136, 2);

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel14.setText("Late Fee Rs.");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(0, 480, 70, 17);

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel15.setText("300.00");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(210, 480, 39, 17);

        jLabel16.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel16.setText("Payment after Due Date");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(0, 510, 138, 17);

        jPanel25.setBackground(new java.awt.Color(0, 0, 0));
        jPanel25.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel25);
        jPanel25.setBounds(160, 520, 100, 2);

        jPanel26.setBackground(new java.awt.Color(0, 0, 0));
        jPanel26.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel26);
        jPanel26.setBounds(215, 1437, 68, 1);

        jPanel29.setBackground(new java.awt.Color(255, 255, 255));
        jPanel29.setLayout(null);

        jLabel22.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel22.setText("Reg No.");
        jLabel22.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel29.add(jLabel22);
        jLabel22.setBounds(0, 0, 45, 20);

        jPanel30.setBackground(new java.awt.Color(0, 0, 0));
        jPanel30.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel29.add(jPanel30);
        jPanel30.setBounds(50, 20, 100, 2);

        jLabel23.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel23.setText("Date:");
        jLabel23.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel29.add(jLabel23);
        jLabel23.setBounds(140, 0, 32, 20);

        jPanel31.setBackground(new java.awt.Color(0, 0, 0));
        jPanel31.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel29.add(jPanel31);
        jPanel31.setBounds(170, 20, 100, 2);

        jLabel24.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel24.setText("Fees for the Month of");
        jLabel24.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel29.add(jLabel24);
        jLabel24.setBounds(0, 27, 121, 20);

        jPanel32.setBackground(new java.awt.Color(0, 0, 0));
        jPanel32.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel29.add(jPanel32);
        jPanel32.setBounds(130, 40, 165, 2);

        jLabel25.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel25.setText("Name:");
        jPanel29.add(jLabel25);
        jLabel25.setBounds(0, 50, 38, 17);

        jPanel33.setBackground(new java.awt.Color(0, 0, 0));
        jPanel33.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel29.add(jPanel33);
        jPanel33.setBounds(50, 60, 290, 2);

        jLabel29.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel29.setText("Class/Section:");
        jPanel29.add(jLabel29);
        jLabel29.setBounds(0, 80, 77, 17);

        jPanel34.setBackground(new java.awt.Color(0, 0, 0));
        jPanel34.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel29.add(jPanel34);
        jPanel34.setBounds(80, 90, 276, 2);

        regNo1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        regNo1.setText("Reg No.");
        jPanel29.add(regNo1);
        regNo1.setBounds(60, 0, 90, 17);

        date1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        date1.setText("Reg No.");
        jPanel29.add(date1);
        date1.setBounds(180, 0, 90, 17);

        month2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        month2.setText("Reg No.");
        month2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel29.add(month2);
        month2.setBounds(130, 20, 120, 20);

        name1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        name1.setText("Reg No.");
        jPanel29.add(name1);
        name1.setBounds(60, 41, 200, 20);

        classes1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        classes1.setText("Reg No.");
        jPanel29.add(classes1);
        classes1.setBounds(100, 70, 150, 17);

        jPanel4.add(jPanel29);
        jPanel29.setBounds(280, 100, 250, 100);

        jPanel35.setBackground(new java.awt.Color(255, 255, 255));
        jPanel35.setLayout(null);

        jLabel30.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel30.setText("Amount");
        jPanel35.add(jLabel30);
        jLabel30.setBounds(200, 10, 45, 17);

        jPanel36.setBackground(new java.awt.Color(0, 0, 0));
        jPanel36.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel36Layout = new javax.swing.GroupLayout(jPanel36);
        jPanel36.setLayout(jPanel36Layout);
        jPanel36Layout.setHorizontalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel36Layout.setVerticalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel35.add(jPanel36);
        jPanel36.setBounds(0, 0, 390, 2);

        jPanel37.setBackground(new java.awt.Color(0, 0, 0));
        jPanel37.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel37Layout = new javax.swing.GroupLayout(jPanel37);
        jPanel37.setLayout(jPanel37Layout);
        jPanel37Layout.setHorizontalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel37Layout.setVerticalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel35.add(jPanel37);
        jPanel37.setBounds(0, 210, 390, 2);

        jPanel38.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel38Layout = new javax.swing.GroupLayout(jPanel38);
        jPanel38.setLayout(jPanel38Layout);
        jPanel38Layout.setHorizontalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        jPanel38Layout.setVerticalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        jPanel35.add(jPanel38);
        jPanel38.setBounds(180, 0, 2, 210);

        jLabel31.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel31.setText("Description");
        jPanel35.add(jLabel31);
        jLabel31.setBounds(10, 10, 64, 17);

        jPanel39.setBackground(new java.awt.Color(0, 0, 0));
        jPanel39.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel39Layout = new javax.swing.GroupLayout(jPanel39);
        jPanel39.setLayout(jPanel39Layout);
        jPanel39Layout.setHorizontalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel39Layout.setVerticalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel35.add(jPanel39);
        jPanel39.setBounds(0, 30, 390, 2);

        jPanel40.setBackground(new java.awt.Color(0, 0, 0));
        jPanel40.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel40Layout = new javax.swing.GroupLayout(jPanel40);
        jPanel40.setLayout(jPanel40Layout);
        jPanel40Layout.setHorizontalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel40Layout.setVerticalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel35.add(jPanel40);
        jPanel40.setBounds(0, 60, 390, 2);

        jPanel41.setBackground(new java.awt.Color(0, 0, 0));
        jPanel41.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel41Layout = new javax.swing.GroupLayout(jPanel41);
        jPanel41.setLayout(jPanel41Layout);
        jPanel41Layout.setHorizontalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel41Layout.setVerticalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel35.add(jPanel41);
        jPanel41.setBounds(0, 90, 390, 2);

        jPanel42.setBackground(new java.awt.Color(0, 0, 0));
        jPanel42.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel42Layout = new javax.swing.GroupLayout(jPanel42);
        jPanel42.setLayout(jPanel42Layout);
        jPanel42Layout.setHorizontalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel42Layout.setVerticalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel35.add(jPanel42);
        jPanel42.setBounds(0, 120, 390, 2);

        jPanel43.setBackground(new java.awt.Color(0, 0, 0));
        jPanel43.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel43Layout = new javax.swing.GroupLayout(jPanel43);
        jPanel43.setLayout(jPanel43Layout);
        jPanel43Layout.setHorizontalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel43Layout.setVerticalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel35.add(jPanel43);
        jPanel43.setBounds(0, 150, 390, 2);

        jPanel44.setBackground(new java.awt.Color(0, 0, 0));
        jPanel44.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel44Layout = new javax.swing.GroupLayout(jPanel44);
        jPanel44.setLayout(jPanel44Layout);
        jPanel44Layout.setHorizontalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel44Layout.setVerticalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel35.add(jPanel44);
        jPanel44.setBounds(0, 180, 390, 2);

        classes6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        classes6.setText("Monthly Fee");
        jPanel35.add(classes6);
        classes6.setBounds(10, 40, 160, 17);

        classes7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        classes7.setText("Registration Fee");
        jPanel35.add(classes7);
        classes7.setBounds(10, 70, 160, 17);

        classes8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        classes8.setText("Discount");
        jPanel35.add(classes8);
        classes8.setBounds(10, 190, 180, 17);

        jLabel20.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel20.setText("Reg No.");
        jPanel35.add(jLabel20);
        jLabel20.setBounds(190, 70, 80, 17);

        p.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        p.setText("jLabel36");
        jPanel35.add(p);
        p.setBounds(190, 100, 70, 17);

        ins.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        ins.setText("jLabel38");
        jPanel35.add(ins);
        ins.setBounds(190, 160, 70, 17);

        in.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        in.setText("jLabel1");
        jPanel35.add(in);
        in.setBounds(190, 130, 50, 20);

        fees1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        fees1.setText("Reg No.");
        jPanel35.add(fees1);
        fees1.setBounds(190, 40, 80, 17);

        instal1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        instal1.setText("jLabel33");
        jPanel35.add(instal1);
        instal1.setBounds(10, 100, 110, 17);

        zz1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        zz1.setText("jLabel37");
        jPanel35.add(zz1);
        zz1.setBounds(10, 160, 140, 17);

        xx1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        xx1.setText("jLabel44");
        jPanel35.add(xx1);
        xx1.setBounds(10, 130, 130, 17);

        jTextField2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel35.add(jTextField2);
        jTextField2.setBounds(182, 180, 100, 30);

        jPanel4.add(jPanel35);
        jPanel35.setBounds(280, 210, 250, 214);

        jLabel32.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel32.setText("Payment before Due Date");
        jPanel4.add(jLabel32);
        jLabel32.setBounds(280, 427, 150, 17);

        jLabel33.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel33.setText(" Due Date");
        jPanel4.add(jLabel33);
        jLabel33.setBounds(280, 450, 60, 17);

        jPanel45.setBackground(new java.awt.Color(0, 0, 0));
        jPanel45.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel45Layout = new javax.swing.GroupLayout(jPanel45);
        jPanel45.setLayout(jPanel45Layout);
        jPanel45Layout.setHorizontalGroup(
            jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanel45Layout.setVerticalGroup(
            jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel45);
        jPanel45.setBounds(376, 460, 140, 2);

        jLabel35.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel35.setText("Late Fee Rs.");
        jPanel4.add(jLabel35);
        jLabel35.setBounds(280, 470, 70, 17);

        pay.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        pay.setText("300.00");
        jPanel4.add(pay);
        pay.setBounds(460, 470, 40, 17);

        jLabel37.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel37.setText("Payment after Due Date");
        jPanel4.add(jLabel37);
        jLabel37.setBounds(280, 500, 140, 17);

        jPanel46.setBackground(new java.awt.Color(0, 0, 0));
        jPanel46.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel46Layout = new javax.swing.GroupLayout(jPanel46);
        jPanel46.setLayout(jPanel46Layout);
        jPanel46Layout.setHorizontalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );
        jPanel46Layout.setVerticalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel46);
        jPanel46.setBounds(440, 510, 85, 2);

        bankstamp.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        bankstamp.setText("Bank Stamp");
        jPanel4.add(bankstamp);
        bankstamp.setBounds(0, 570, 67, 17);

        jLabel39.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel39.setText("School Head");
        jPanel4.add(jLabel39);
        jLabel39.setBounds(186, 570, 90, 17);

        l.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        l.setText("Late Fee Rs.");
        jPanel4.add(l);
        l.setBounds(540, 480, 68, 17);

        g.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        g.setText("300.00");
        jPanel4.add(g);
        g.setBounds(720, 480, 40, 17);

        jPanel53.setBackground(new java.awt.Color(255, 255, 255));
        jPanel53.setLayout(null);

        jLabel45.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel45.setText("Amount");
        jPanel53.add(jLabel45);
        jLabel45.setBounds(190, 10, 45, 17);

        jPanel54.setBackground(new java.awt.Color(0, 0, 0));
        jPanel54.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel54Layout = new javax.swing.GroupLayout(jPanel54);
        jPanel54.setLayout(jPanel54Layout);
        jPanel54Layout.setHorizontalGroup(
            jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel54Layout.setVerticalGroup(
            jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel53.add(jPanel54);
        jPanel54.setBounds(0, 0, 390, 2);

        jPanel55.setBackground(new java.awt.Color(0, 0, 0));
        jPanel55.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel55Layout = new javax.swing.GroupLayout(jPanel55);
        jPanel55.setLayout(jPanel55Layout);
        jPanel55Layout.setHorizontalGroup(
            jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel55Layout.setVerticalGroup(
            jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel53.add(jPanel55);
        jPanel55.setBounds(0, 210, 390, 2);

        jPanel56.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel56Layout = new javax.swing.GroupLayout(jPanel56);
        jPanel56.setLayout(jPanel56Layout);
        jPanel56Layout.setHorizontalGroup(
            jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        jPanel56Layout.setVerticalGroup(
            jPanel56Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        jPanel53.add(jPanel56);
        jPanel56.setBounds(170, 0, 2, 210);

        jLabel46.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel46.setText("Description");
        jPanel53.add(jLabel46);
        jLabel46.setBounds(10, 10, 64, 17);

        jPanel57.setBackground(new java.awt.Color(0, 0, 0));
        jPanel57.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel57Layout = new javax.swing.GroupLayout(jPanel57);
        jPanel57.setLayout(jPanel57Layout);
        jPanel57Layout.setHorizontalGroup(
            jPanel57Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel57Layout.setVerticalGroup(
            jPanel57Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel53.add(jPanel57);
        jPanel57.setBounds(0, 30, 390, 2);

        jPanel58.setBackground(new java.awt.Color(0, 0, 0));
        jPanel58.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel58Layout = new javax.swing.GroupLayout(jPanel58);
        jPanel58.setLayout(jPanel58Layout);
        jPanel58Layout.setHorizontalGroup(
            jPanel58Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel58Layout.setVerticalGroup(
            jPanel58Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel53.add(jPanel58);
        jPanel58.setBounds(0, 60, 390, 2);

        jPanel59.setBackground(new java.awt.Color(0, 0, 0));
        jPanel59.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel59Layout = new javax.swing.GroupLayout(jPanel59);
        jPanel59.setLayout(jPanel59Layout);
        jPanel59Layout.setHorizontalGroup(
            jPanel59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel59Layout.setVerticalGroup(
            jPanel59Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel53.add(jPanel59);
        jPanel59.setBounds(0, 90, 390, 2);

        jPanel60.setBackground(new java.awt.Color(0, 0, 0));
        jPanel60.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel60Layout = new javax.swing.GroupLayout(jPanel60);
        jPanel60.setLayout(jPanel60Layout);
        jPanel60Layout.setHorizontalGroup(
            jPanel60Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel60Layout.setVerticalGroup(
            jPanel60Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel53.add(jPanel60);
        jPanel60.setBounds(0, 120, 390, 2);

        jPanel61.setBackground(new java.awt.Color(0, 0, 0));
        jPanel61.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel61Layout = new javax.swing.GroupLayout(jPanel61);
        jPanel61.setLayout(jPanel61Layout);
        jPanel61Layout.setHorizontalGroup(
            jPanel61Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel61Layout.setVerticalGroup(
            jPanel61Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel53.add(jPanel61);
        jPanel61.setBounds(0, 150, 390, 2);

        jPanel62.setBackground(new java.awt.Color(0, 0, 0));
        jPanel62.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel62Layout = new javax.swing.GroupLayout(jPanel62);
        jPanel62.setLayout(jPanel62Layout);
        jPanel62Layout.setHorizontalGroup(
            jPanel62Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel62Layout.setVerticalGroup(
            jPanel62Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel53.add(jPanel62);
        jPanel62.setBounds(0, 180, 390, 2);

        classes9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        classes9.setText("Monthly Fee");
        jPanel53.add(classes9);
        classes9.setBounds(10, 40, 160, 17);

        jLabel19.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel19.setText("Reg No.");
        jPanel53.add(jLabel19);
        jLabel19.setBounds(180, 70, 80, 17);

        classes10.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        classes10.setText("Registration Fee");
        jPanel53.add(classes10);
        classes10.setBounds(10, 70, 160, 17);

        classes11.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        classes11.setText("Discount");
        jPanel53.add(classes11);
        classes11.setBounds(10, 190, 160, 17);

        fees2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        fees2.setText("Reg No.");
        jPanel53.add(fees2);
        fees2.setBounds(180, 40, 80, 17);

        p1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        p1.setText("jLabel36");
        jPanel53.add(p1);
        p1.setBounds(180, 100, 70, 17);

        in1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        in1.setText("jLabel1");
        jPanel53.add(in1);
        in1.setBounds(180, 130, 50, 20);

        ins1.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        ins1.setText("jLabel38");
        jPanel53.add(ins1);
        ins1.setBounds(180, 160, 70, 17);

        instal2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        instal2.setText("jLabel33");
        jPanel53.add(instal2);
        instal2.setBounds(10, 100, 110, 17);

        zz2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        zz2.setText("jLabel37");
        jPanel53.add(zz2);
        zz2.setBounds(10, 160, 140, 17);

        xx2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        xx2.setText("jLabel44");
        jPanel53.add(xx2);
        xx2.setBounds(10, 130, 130, 17);

        jTextField3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jTextField3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel53.add(jTextField3);
        jTextField3.setBounds(170, 180, 110, 30);

        jPanel4.add(jPanel53);
        jPanel53.setBounds(540, 210, 250, 213);

        jLabel48.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel48.setText(" Due Date");
        jPanel4.add(jLabel48);
        jLabel48.setBounds(540, 460, 57, 17);

        bank2.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        bank2.setText(" BANK AL HABIB LIMITED, FORT CORNER BRANCH");
        jPanel4.add(bank2);
        bank2.setBounds(540, 50, 260, 16);

        jPanel47.setBackground(new java.awt.Color(255, 255, 255));
        jPanel47.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("Reg No.");
        jPanel47.add(jLabel5);
        jLabel5.setBounds(0, 0, 45, 17);

        jPanel48.setBackground(new java.awt.Color(0, 0, 0));
        jPanel48.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel48Layout = new javax.swing.GroupLayout(jPanel48);
        jPanel48.setLayout(jPanel48Layout);
        jPanel48Layout.setHorizontalGroup(
            jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel48Layout.setVerticalGroup(
            jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel47.add(jPanel48);
        jPanel48.setBounds(50, 20, 100, 2);

        jLabel41.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel41.setText("Date:");
        jPanel47.add(jLabel41);
        jLabel41.setBounds(150, 0, 32, 17);

        jLabel42.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel42.setText("Fees for the Month of");
        jPanel47.add(jLabel42);
        jLabel42.setBounds(0, 30, 121, 17);

        jPanel50.setBackground(new java.awt.Color(0, 0, 0));
        jPanel50.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel50Layout = new javax.swing.GroupLayout(jPanel50);
        jPanel50.setLayout(jPanel50Layout);
        jPanel50Layout.setHorizontalGroup(
            jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 195, Short.MAX_VALUE)
        );
        jPanel50Layout.setVerticalGroup(
            jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel47.add(jPanel50);
        jPanel50.setBounds(150, 50, 195, 2);

        jLabel43.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel43.setText("Name:");
        jPanel47.add(jLabel43);
        jLabel43.setBounds(0, 50, 38, 17);

        jPanel51.setBackground(new java.awt.Color(0, 0, 0));
        jPanel51.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel51Layout = new javax.swing.GroupLayout(jPanel51);
        jPanel51.setLayout(jPanel51Layout);
        jPanel51Layout.setHorizontalGroup(
            jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        jPanel51Layout.setVerticalGroup(
            jPanel51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel47.add(jPanel51);
        jPanel51.setBounds(60, 70, 290, 2);

        jLabel44.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel44.setText("Class/Section:");
        jPanel47.add(jLabel44);
        jLabel44.setBounds(0, 80, 77, 17);

        jPanel52.setBackground(new java.awt.Color(0, 0, 0));
        jPanel52.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel52Layout = new javax.swing.GroupLayout(jPanel52);
        jPanel52.setLayout(jPanel52Layout);
        jPanel52Layout.setHorizontalGroup(
            jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );
        jPanel52Layout.setVerticalGroup(
            jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel47.add(jPanel52);
        jPanel52.setBounds(80, 100, 276, 2);

        regNo3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        regNo3.setText("Reg No.");
        jPanel47.add(regNo3);
        regNo3.setBounds(60, 0, 90, 17);

        date2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        date2.setText("Reg No.");
        jPanel47.add(date2);
        date2.setBounds(190, 0, 70, 17);

        month3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        month3.setText("Reg No.");
        jPanel47.add(month3);
        month3.setBounds(130, 30, 150, 17);

        name2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        name2.setText("Reg No.");
        jPanel47.add(name2);
        name2.setBounds(70, 50, 210, 17);

        classes2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        classes2.setText("Reg No.");
        jPanel47.add(classes2);
        classes2.setBounds(110, 80, 170, 17);

        jPanel49.setBackground(new java.awt.Color(0, 0, 0));
        jPanel49.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel49Layout = new javax.swing.GroupLayout(jPanel49);
        jPanel49.setLayout(jPanel49Layout);
        jPanel49Layout.setHorizontalGroup(
            jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel49Layout.setVerticalGroup(
            jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel47.add(jPanel49);
        jPanel49.setBounds(180, 20, 100, 2);

        jPanel4.add(jPanel47);
        jPanel47.setBounds(540, 100, 250, 110);

        jLabel53.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel53.setText("School Head");
        jPanel4.add(jLabel53);
        jLabel53.setBounds(690, 570, 70, 17);

        acountnu2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        acountnu2.setText("1109-0981-008405-01-7");
        jPanel4.add(acountnu2);
        acountnu2.setBounds(540, 80, 260, 21);
        jPanel4.add(jLabel40);
        jLabel40.setBounds(722, 1, 0, 43);

        challanpayable2.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        challanpayable2.setText(" (Challan payable at any branch of Bank Al Habib)");
        jPanel4.add(challanpayable2);
        challanpayable2.setBounds(540, 60, 280, 16);

        mobno2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        mobno2.setText("            Mob: 0333-012371, 0334-0123771");
        jPanel4.add(mobno2);
        mobno2.setBounds(540, 40, 270, 10);

        jLabel47.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel47.setText("Payment before Due Date");
        jPanel4.add(jLabel47);
        jLabel47.setBounds(540, 430, 150, 17);

        jPanel63.setBackground(new java.awt.Color(0, 0, 0));
        jPanel63.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel63Layout = new javax.swing.GroupLayout(jPanel63);
        jPanel63.setLayout(jPanel63Layout);
        jPanel63Layout.setHorizontalGroup(
            jPanel63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        jPanel63Layout.setVerticalGroup(
            jPanel63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel63);
        jPanel63.setBounds(630, 470, 130, 2);

        jPanel64.setBackground(new java.awt.Color(0, 0, 0));
        jPanel64.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel64Layout = new javax.swing.GroupLayout(jPanel64);
        jPanel64.setLayout(jPanel64Layout);
        jPanel64Layout.setHorizontalGroup(
            jPanel64Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel64Layout.setVerticalGroup(
            jPanel64Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel64);
        jPanel64.setBounds(690, 520, 90, 2);

        jLabel50.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel50.setText("Payment after Due Date");
        jPanel4.add(jLabel50);
        jLabel50.setBounds(540, 510, 140, 17);

        jPanel65.setBackground(new java.awt.Color(0, 0, 0));
        jPanel65.setPreferredSize(new java.awt.Dimension(2, 100));

        javax.swing.GroupLayout jPanel65Layout = new javax.swing.GroupLayout(jPanel65);
        jPanel65.setLayout(jPanel65Layout);
        jPanel65Layout.setHorizontalGroup(
            jPanel65Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        jPanel65Layout.setVerticalGroup(
            jPanel65Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel65);
        jPanel65.setBounds(530, 10, 2, 680);

        acountnu3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        acountnu3.setText("1109-0981-008405-01-7");
        jPanel4.add(acountnu3);
        acountnu3.setBounds(280, 80, 250, 26);

        challanpayable3.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        challanpayable3.setText(" (Challan payable at any branch of Bank Al Habib)");
        jPanel4.add(challanpayable3);
        challanpayable3.setBounds(280, 70, 280, 16);

        bank3.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        bank3.setText(" BANK AL HABIB LIMITED, FORT CORNER BRANCH");
        jPanel4.add(bank3);
        bank3.setBounds(280, 60, 250, 16);

        mobno3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        mobno3.setText("     Mob: 0333-012371, 0334-0123771");
        jPanel4.add(mobno3);
        mobno3.setBounds(290, 40, 210, 16);

        jLabel54.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel54.setText("Bank Stamp");
        jPanel4.add(jLabel54);
        jLabel54.setBounds(540, 570, 70, 17);

        jLabel55.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel55.setText("School Head");
        jPanel4.add(jLabel55);
        jLabel55.setBounds(440, 570, 70, 17);

        jLabel56.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel56.setText("Bank Stamp");
        jPanel4.add(jLabel56);
        jLabel56.setBounds(280, 570, 70, 17);

        total.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        total.setText("jLabel1");
        total.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel4.add(total);
        total.setBounds(200, 420, 50, 20);

        jLabel51.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel51.setText("jLabel1");
        jPanel4.add(jLabel51);
        jLabel51.setBounds(140, 450, 78, 20);

        afterFees.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        afterFees.setText("Reg No.");
        jPanel4.add(afterFees);
        afterFees.setBounds(450, 490, 80, 17);

        afterFees1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        afterFees1.setText("Reg No.");
        jPanel4.add(afterFees1);
        afterFees1.setBounds(170, 500, 80, 20);

        afterFees2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        afterFees2.setText("Reg No.");
        jPanel4.add(afterFees2);
        afterFees2.setBounds(720, 500, 60, 17);

        total1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        total1.setText("jLabel1");
        jPanel4.add(total1);
        total1.setBounds(470, 420, 50, 20);

        due.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        due.setText("jLabel1");
        jPanel4.add(due);
        due.setBounds(410, 440, 110, 20);

        total2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        total2.setText("jLabel1");
        jPanel4.add(total2);
        total2.setBounds(720, 430, 50, 20);

        due1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        due1.setText("jLabel1");
        jPanel4.add(due1);
        due1.setBounds(640, 450, 70, 20);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel1.setText("School  Copy");
        jLabel1.setToolTipText("");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel4.add(jLabel1);
        jLabel1.setBounds(450, 0, 70, 20);

        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/cha.PNG"))); // NOI18N
        jLabel57.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel4.add(jLabel57);
        jLabel57.setBounds(280, 10, 210, 40);

        jLabel17.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel17.setText("Parent  Copy");
        jLabel17.setToolTipText("");
        jLabel17.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel4.add(jLabel17);
        jLabel17.setBounds(200, 0, 70, 20);

        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/cha.PNG"))); // NOI18N
        jPanel4.add(jLabel58);
        jLabel58.setBounds(10, 0, 210, 42);

        jLabel18.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel18.setText("Bank  Copy");
        jLabel18.setToolTipText("");
        jLabel18.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel4.add(jLabel18);
        jLabel18.setBounds(720, 0, 60, 40);

        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/cha.PNG"))); // NOI18N
        jLabel59.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel4.add(jLabel59);
        jLabel59.setBounds(550, 10, 210, 40);

        javax.swing.GroupLayout printpictureLayout = new javax.swing.GroupLayout(printpicture);
        printpicture.setLayout(printpictureLayout);
        printpictureLayout.setHorizontalGroup(
            printpictureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(printpictureLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                .addContainerGap())
        );
        printpictureLayout.setVerticalGroup(
            printpictureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, printpictureLayout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(317, 317, 317)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(printpicture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(printpicture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 892, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        childPanel=new adminHomePanel();
        childPanel.setSize(this.getSize());
        this.removeAll();
        this.repaint();
        this.add(childPanel);
        this.validate();
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        ADMIN.printComponenet(jPanel4);
        Finance fin=new Finance();
        fin.updateDuesStudentFinancefees(regNo.getText(),Double.parseDouble(jTextField1.getText()), String.valueOf(mon), String.valueOf(ye));
        //        Graphics pg;
        //       try{
            //           Document doc=new Document();
            ////           try {
                ////    PdfWriter writer = PdfWriter.getInstance(doc, new FileOutputStream("C:\\Users\\Muhammad Faraz\\Desktop\\JavaApplication1\\test.pdf"));
                ////    doc.open();
                ////    PdfContentByte contentByte = writer.getDirectContent();
                ////    PdfTemplate template = contentByte.createTemplate(500, 500);
                ////    Graphics2D g2 = template.createGraphics(500, 500);
                ////    printpicture.print(g2);
                ////    g2.dispose();
                ////    contentByte.addTemplate(template, 30, 300);
                ////               System.out.println("done");
                ////} catch (Exception e) {
                ////    e.printStackTrace();
                ////}
            ////finally{
                ////    if(doc.isOpen()){
                    ////        doc.close();
                    ////    }}
            ////           PdfWriter.getInstance(doc, new FileOutputStream("fya.pdf"));
            ////           doc.open();
            ////           Graphics2D g2 = (Graphics2D) pg;
            ////      g2.translate(pf.getImageableX(), pf.getImageableY());
            ////      String name="ID   ";
            ////        System.out.println("");
            //
            //
            ////      component.paint(g2);
            ////PdfWriter writer = PdfWriter.getInstance(doc, new FileOutputStream("C:\\Users\\Muhammad Faraz\\Desktop\\JavaApplication1\\test.pdf"));
            ////    doc.open();
            ////           PdfContentByte contentByte = writer.getDirectContent();
            ////           PdfTemplate template = contentByte.createTemplate(500, 500);
            ////    Graphics2D g2 = template.createGraphics(500, 500);
            ////    printpicture.print(g2);
            ////    g2.dispose();
            ////    contentByte.addTemplate(template, 30, 300);
            //
            ////           System.out.println("done");
            //      }catch(Exception e){
            //            JOptionPane.showMessageDialog(null, e);
            //        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MousePressed

    private void jPanel6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseReleased

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        //        int cal=Integer.parseInt(in3.getText())+Integer.parseInt(jLabel38.getText())+Integer.parseInt(jLabel36.getText())
        double cal=Double.parseDouble(total.getText())-Double.parseDouble(jTextField1.getText());
        total.setText(String.valueOf(cal));
        total1.setText(String.valueOf(cal));
        total2.setText(String.valueOf(cal));
        double u=Double.parseDouble(jTextField1.getText());
        jTextField2.setText(String.valueOf(u));
        jTextField3.setText(String.valueOf(u));
        double lat=cal+300;
        afterFees.setText(String.valueOf(lat));
        afterFees1.setText(String.valueOf(lat));
        afterFees2.setText(String.valueOf(lat));
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
        double cal=Double.parseDouble(total1.getText())-Double.parseDouble(jTextField2.getText());
        total1.setText(String.valueOf(cal));
        total.setText(String.valueOf(cal));
        total2.setText(String.valueOf(cal));
        double u=Double.parseDouble(jTextField2.getText());
        jTextField1.setText(String.valueOf(u));
        jTextField3.setText(String.valueOf(u));double lat=cal+300;
        afterFees.setText(String.valueOf(lat));
        afterFees1.setText(String.valueOf(lat));
        afterFees2.setText(String.valueOf(lat));
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
        double cal=Double.parseDouble(total2.getText())-Double.parseDouble(jTextField2.getText());
        total2.setText(String.valueOf(cal));
        total.setText(String.valueOf(cal));
        total1.setText(String.valueOf(cal));
        double u=Double.parseDouble(jTextField3.getText());
        jTextField2.setText(String.valueOf(u));
        jTextField1.setText(String.valueOf(u));double lat=cal+300;
        afterFees.setText(String.valueOf(lat));
        afterFees1.setText(String.valueOf(lat));
        afterFees2.setText(String.valueOf(lat));
    }//GEN-LAST:event_jTextField3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Date;
    private javax.swing.JLabel acountnu;
    private javax.swing.JLabel acountnu2;
    private javax.swing.JLabel acountnu3;
    private javax.swing.JLabel afterFees;
    private javax.swing.JLabel afterFees1;
    private javax.swing.JLabel afterFees2;
    private javax.swing.JLabel bank;
    private javax.swing.JLabel bank2;
    private javax.swing.JLabel bank3;
    private javax.swing.JLabel bankstamp;
    private javax.swing.JLabel challanpayable;
    private javax.swing.JLabel challanpayable2;
    private javax.swing.JLabel challanpayable3;
    private javax.swing.JLabel classes;
    private javax.swing.JLabel classes1;
    private javax.swing.JLabel classes10;
    private javax.swing.JLabel classes11;
    private javax.swing.JLabel classes2;
    private javax.swing.JLabel classes3;
    private javax.swing.JLabel classes4;
    private javax.swing.JLabel classes5;
    private javax.swing.JLabel classes6;
    private javax.swing.JLabel classes7;
    private javax.swing.JLabel classes8;
    private javax.swing.JLabel classes9;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel date2;
    private javax.swing.JLabel due;
    private javax.swing.JLabel due1;
    private javax.swing.JLabel fees;
    private javax.swing.JLabel fees1;
    private javax.swing.JLabel fees2;
    private javax.swing.JLabel g;
    private javax.swing.JLabel in;
    private javax.swing.JLabel in1;
    private javax.swing.JLabel in3;
    public javax.swing.JLabel ins;
    public javax.swing.JLabel ins1;
    public javax.swing.JLabel instal;
    public javax.swing.JLabel instal1;
    public javax.swing.JLabel instal2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    public javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    public javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    public javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JPanel jPanel59;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel60;
    private javax.swing.JPanel jPanel61;
    private javax.swing.JPanel jPanel62;
    private javax.swing.JPanel jPanel63;
    private javax.swing.JPanel jPanel64;
    private javax.swing.JPanel jPanel65;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel l;
    private javax.swing.JLabel mobno;
    private javax.swing.JLabel mobno2;
    private javax.swing.JLabel mobno3;
    private javax.swing.JLabel month;
    private javax.swing.JLabel month2;
    private javax.swing.JLabel month3;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    public javax.swing.JLabel p;
    public javax.swing.JLabel p1;
    private javax.swing.JLabel pay;
    private javax.swing.JPanel printpicture;
    private javax.swing.JLabel regFees;
    private javax.swing.JLabel regNo;
    private javax.swing.JLabel regNo1;
    private javax.swing.JLabel regNo3;
    private javax.swing.JLabel total;
    private javax.swing.JLabel total1;
    private javax.swing.JLabel total2;
    public javax.swing.JLabel xx;
    public javax.swing.JLabel xx1;
    public javax.swing.JLabel xx2;
    public javax.swing.JLabel zz;
    public javax.swing.JLabel zz1;
    public javax.swing.JLabel zz2;
    // End of variables declaration//GEN-END:variables
}
