/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import code.Staff;
import code.Student;
import code.admissionChallan;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Muhammad Faraz
 */
public class adchallanpay extends javax.swing.JPanel {

    /**
     * Creates new form adchallanpay
     */
    JPanel childPanel;
    
    Student st=new Student();
    public adchallanpay() {
        initComponents();
        st.StudentRecord(jTable1);
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        name = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel31 = new javax.swing.JLabel();
        addbtn2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        idnotf1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel30 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        addbtn3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        clas = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jSeparator30 = new javax.swing.JSeparator();
        sec = new javax.swing.JTextField();
        jSeparator29 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1163, 750));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1163, 750));

        jLabel33.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel33.setText("SELECTED STUDENT INFORMATION");

        name.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        name.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 51, 51));
        jLabel31.setText("NAME");

        addbtn2.setBackground(new java.awt.Color(51, 153, 255));
        addbtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addbtn2MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/icons8-search-40.png"))); // NOI18N
        jLabel6.setText("SEARCH");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout addbtn2Layout = new javax.swing.GroupLayout(addbtn2);
        addbtn2.setLayout(addbtn2Layout);
        addbtn2Layout.setHorizontalGroup(
            addbtn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addbtn2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel6)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        addbtn2Layout.setVerticalGroup(
            addbtn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addbtn2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        idnotf1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        idnotf1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        idnotf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idnotf1ActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 51));
        jLabel28.setText("ID");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionBackground(new java.awt.Color(51, 153, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel30.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 51, 51));
        jLabel30.setText("ID");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/icons8-back-48.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setText("ADMISSION FEE ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        id.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        id.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        addbtn3.setBackground(new java.awt.Color(51, 153, 255));
        addbtn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addbtn3MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("GENERATE  CHALLAN");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout addbtn3Layout = new javax.swing.GroupLayout(addbtn3);
        addbtn3.setLayout(addbtn3Layout);
        addbtn3Layout.setHorizontalGroup(
            addbtn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addbtn3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addbtn3Layout.setVerticalGroup(
            addbtn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addbtn3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel34.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(51, 51, 51));
        jLabel34.setText("CLASS");

        clas.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        clas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        clas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clasActionPerformed(evt);
            }
        });
        clas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                clasKeyTyped(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(51, 51, 51));
        jLabel36.setText("SECTION");

        sec.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        sec.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        sec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secActionPerformed(evt);
            }
        });
        sec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                secKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel28)
                            .addComponent(idnotf1, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(jSeparator1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clas, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator29, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sec, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator30, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel31)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(name)
                                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel30)
                                        .addComponent(id)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(addbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(51, 51, 51)))
                        .addGap(0, 101, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idnotf1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(addbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addGap(7, 7, 7)
                                .addComponent(sec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jSeparator30, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addGap(7, 7, 7)
                                .addComponent(clas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jSeparator29, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        //           String monthse=(String)this.monthsea.getSelectedItem();
        //        String year=(String)this.yearsearch.getSelectedItem();
        //         String pa=(String)pay.getSelectedItem();
        //      if (pa.equals("PAID")){
            //         pa="0"  ;
            //        }
        //        else {
            //            pa="1";
            //        }
        //          if (idserch.getText().equals("")&&namesearch.getText().equals("")&&monthse.equals(" ")&&year.equals(" ")){
            //              JOptionPane.showMessageDialog( this, "PLEASE ENTER All ","Error", JOptionPane.ERROR_MESSAGE);
            //          return;
            //          }
        //
        //       StudentFeesChallan st=new StudentFeesChallan();
        ////       int m=0;
        //       Staff staff=new Staff();
        ////        m=staff.getMonthInt(m,monthse);
        //////        if (id)
        ////Staff st=new Staff();
        //        int m=0;
        //        m=staff.getMonthInt(m,monthse);
        //if (idserch.getText()==("")&&namesearch.getText().equals("")&&monthse.equals(" ")&&year.equals(" ") && pa!=(" ")){
            //    stu.StudentFeesConditionpay(jTable1, pa);
            //    return;
            //}
        //if (idserch.getText()!=("")&&namesearch.getText().equals("")&&monthse.equals(" ")&&year.equals(" ") && pa!=(" ")){
            //    stu.StudentFeesConditionidpay(jTable1, idserch.getText(),pa);
            //    return;
            //}
        //
        //if (idserch.getText().equals("")&&namesearch.getText()!=("")&&monthse.equals(" ")&&year.equals(" ") && pa!=(" ")){
            //    stu.StudentFeesConditionpayname(jTable1, pa,namesearch.getText());
            //    return;
            //}
        //
        //if (idserch.getText().equals("")&&namesearch.getText().equals("")&&monthse!=(" ")&&year.equals(" ") && pa!=(" ")){
            //    stu.StudentFeesConditionpaymonth(jTable1, pa,String.valueOf(m));
            //    return;
            //}
        //if (idserch.getText().equals("")&&namesearch.getText().equals("")&&monthse==(" ")&&year!=(" ") && pa!=(" ")){
            //    stu.StudentFeesConditionpayyear(jTable1, pa,year);
            //    return;
            //}
        //
        //
        //        if (idserch.getText()!=""&&namesearch.getText().equals("")&&monthse.equals(" ")&&year.equals(" ") && pa.equals(" ")){
            ////              JOptionPane.showMessageDialog( this, "PLEASE ENTER All ","Error", JOptionPane.ERROR_MESSAGE);
            ////          return;
            //if (st.searchstudentfeesid(idserch.getText())){
                //st.StudentFeesConditionid(jTable1, idserch.getText());
                //return;}
            //else{
                //    JOptionPane.showMessageDialog(null, "NOT FOUND","STUDENT",JOptionPane.INFORMATION_MESSAGE);
                //
                //        stu.StudentRecordfees(jTable1);return;
                //}
            //          }
        //        if (idserch.getText().equals("")&&namesearch.getText()!=""&&monthse.equals(" ")&&year.equals(" ")){
            //     if (st.searchstudentfeesname(namesearch.getText())){         st.StudentFeesConditionname(jTable1, namesearch.getText());//jTable1);
            //              return;}
        //     else {
            //
            //    JOptionPane.showMessageDialog(null, "NOT FOUND","STUDENT",JOptionPane.INFORMATION_MESSAGE);
            //        stu.StudentRecordfees(jTable1);
            // return;
            //     }
        //          }
        //        if (idserch.getText().equals("")&&namesearch.getText().equals("")&&monthse!=" "&&year.equals(" ")&& pa.equals(" ")){
            ////              JOptionPane.showMessageDialog( this, "PLEASE ENTER All ","Error", JOptionPane.ERROR_MESSAGE);
            //           if (st.searchstudentfeesmonth(monthse)){ st.StudentFeesConditionmonth(jTable1,monthse);
                //return;}else {
                //
                //    JOptionPane.showMessageDialog(null, "NOT FOUND","STUDENT",JOptionPane.INFORMATION_MESSAGE);
                //        stu.StudentRecordfees(jTable1);
                // return;
                //           }
            //          }
        //        if (idserch.getText().equals("")&&namesearch.getText().equals("")&&monthse==" "&&year!=" "&& pa.equals(" ")){
            ////              JOptionPane.showMessageDialog( this, "PLEASE ENTER All ","Error", JOptionPane.ERROR_MESSAGE);
            //         if (st.searchstudentfeesyear(year)){   st.StudentFeesConditionyear(jTable1, year);
                //return;}else {
                //
                //    JOptionPane.showMessageDialog(null, "NOT FOUND","STUDENT",JOptionPane.INFORMATION_MESSAGE);
                //        stu.StudentRecordfees(jTable1);
                // return;
                //         }
            //          }
        //        if (idserch.getText()!=""&&namesearch.getText()!=""&&monthse==" "&&year.equals(" ")&& pa.equals(" ")){
            ////              JOptionPane.showMessageDialog( this, "PLEASE ENTER All ","Error", JOptionPane.ERROR_MESSAGE);
            //        if (st.searchstudentfeesidname(idserch.getText(), namesearch.getText())){    st.StudentFeesConditionidName(jTable1, idserch.getText(),namesearch.getText());
                //return;
                //          }
            //        else {
                //
                //    JOptionPane.showMessageDialog(null, "NOT FOUND","STUDENT",JOptionPane.INFORMATION_MESSAGE);
                //        stu.StudentRecordfees(jTable1);
                // return;
                //        }}
        //
        //        if (idserch.getText()!=""&&namesearch.getText()==""&&monthse!=" "&&year.equals(" ")&& pa.equals(" ")){
            ////              JOptionPane.showMessageDialog( this, "PLEASE ENTER All ","Error", JOptionPane.ERROR_MESSAGE);
            //          if (st.searchstudentfeesidmonth(idserch.getText(), String.valueOf(m))){  st.StudentFeesConditionidMonth(jTable1, idserch.getText(),String.valueOf(m));
                //return;}
            //          else {
                //
                //    JOptionPane.showMessageDialog(null, "NOT FOUND","STUDENT",JOptionPane.INFORMATION_MESSAGE);
                //        stu.StudentRecordfees(jTable1);
                // return;
                //          }
            //          }
        //
        //        if (idserch.getText()!=""&&namesearch.getText()==""&&monthse==" "&&year!=(" ") && pa.equals(" ")){
            ////              JOptionPane.showMessageDialog( this, "PLEASE ENTER All ","Error", JOptionPane.ERROR_MESSAGE);
            //           if (st.searchstudentfeesidyear(idserch.getText(), year)){ st.StudentFeesConditionidYear(jTable1, idserch.getText(),year);
                //return;}
            //           else {
                //
                //    JOptionPane.showMessageDialog(null, "NOT FOUND","STUDENT",JOptionPane.INFORMATION_MESSAGE);
                //        stu.StudentRecordfees(jTable1);
                // return;
                //           }
            //          }
        //
        //        if (idserch.getText().equals("")&&namesearch.getText()!=""&&monthse!=" "&&year.equals(" ")&& pa.equals(" ")){
            ////              JOptionPane.showMessageDialog( this, "PLEASE ENTER All ","Error", JOptionPane.ERROR_MESSAGE);
            //          if (st.searchstudentfeesnamemonth(namesearch.getText(), String.valueOf(m))){  st.StudentFeesConditionNameMonth(jTable1, namesearch.getText(),String.valueOf(m));
                //return;}
            //          else{
                //
                //    JOptionPane.showMessageDialog(null, "NOT FOUND","STUDENT",JOptionPane.INFORMATION_MESSAGE);
                //        stu.StudentRecordfees(jTable1);
                // return;
                //          }
            //          }
        //
        //        if (idserch.getText().equals("")&&namesearch.getText()!=""&&monthse==" "&&year !=(" ")&& pa.equals(" ")){
            ////              JOptionPane.showMessageDialog( this, "PLEASE ENTER All ","Error", JOptionPane.ERROR_MESSAGE);
            //if (st.searchstudentfeesnameyear(namesearch.getText(), year)){
                //            st.StudentFeesConditionNameYear(jTable1, namesearch.getText(),year);
                //return;}
            //else {
                //
                //    JOptionPane.showMessageDialog(null, "NOT FOUND","STUDENT",JOptionPane.INFORMATION_MESSAGE);
                //        stu.StudentRecordfees(jTable1);
                // return;
                //}
            //          }
        //
        //        if (idserch.getText().equals("")&&namesearch.getText().equals("")&&monthse!=" "&&year!=(" ")&& pa.equals(" ")){
            ////              JOptionPane.showMessageDialog( this, "PLEASE ENTER All ","Error", JOptionPane.ERROR_MESSAGE);
            //if(st.searchstudentfeesmonthyear(String.valueOf(m), year)){
                //            st.StudentFeesConditionMonthYear(jTable1,String.valueOf(m) , year);
                ////JOptionPane.showMessageDialog(null, "found");//Year(jTable1, namesearch.getText(),year);
                //return;}else {
                //
                //    JOptionPane.showMessageDialog(null, "NOT FOUND","STUDENT",JOptionPane.INFORMATION_MESSAGE);
                //        stu.StudentRecordfees(jTable1);
                // return;
                //        }
            //          }
        //
        //        if (idserch.getText()!=""&&namesearch.getText()!=""&&monthse!=(" ")&&year.equals(" ")&& pa.equals(" ")){
            ////              JOptionPane.showMessageDialog( this, "PLEASE ENTER All ","Error", JOptionPane.ERROR_MESSAGE);
            //if (st.searchstudentfeesidnamemonth(idserch.getText(), namesearch.getText(), String.valueOf(m))){
                //            st.StudentFeesConditionidNameMonth(jTable1, idserch.getText(),namesearch.getText(),String.valueOf(m));
                //return;}
            //else {
                //
                //    JOptionPane.showMessageDialog(null, "NOT FOUND","STUDENT",JOptionPane.INFORMATION_MESSAGE);
                //        stu.StudentRecordfees(jTable1);
                // return;
                //}
            //          }
        //
        //        if (idserch.getText()!=""&&namesearch.getText()!=""&&monthse==" "&&year!=(" ")&& pa.equals(" ")){
            ////              JOptionPane.showMessageDialog( this, "PLEASE ENTER All ","Error", JOptionPane.ERROR_MESSAGE);
            //if (st.searchstudentfeesidmonthyear(idserch.getText(),monthse, year)){
                //            st.StudentFeesConditionIdMonthYear(jTable1, idserch.getText(),monthse,year);
                //return;}
            //else {
                //
                //    JOptionPane.showMessageDialog(null, "NOT FOUND","STUDENT",JOptionPane.INFORMATION_MESSAGE);
                //        stu.StudentRecordfees(jTable1);
                // return;
                //}
            //          }
        //
        //        if (idserch.getText().equals("")&&namesearch.getText()!=""&&monthse!=(" ")&&year!=(" ")&& pa.equals(" ")){
            ////              JOptionPane.showMessageDialog( this, "PLEASE ENTER All ","Error", JOptionPane.ERROR_MESSAGE);
            //        if (st.searchstudentfeesnamemonthyear(namesearch.getText(), String.valueOf(m), year)){    st.StudentFeesConditionNameMonthYear(jTable1, namesearch.getText(),String.valueOf(m),year);
                //return;}
            //        else {
                //
                //    JOptionPane.showMessageDialog(null, "NOT FOUND","STUDENT",JOptionPane.INFORMATION_MESSAGE);
                //        stu.StudentRecordfees(jTable1);
                // return;
                //        }
            //          }
        //
        //        if (idserch.getText()!=""&&namesearch.getText()!=""&&monthse!=" "&&year!=(" ")&& pa.equals(" ")){
            ////              JOptionPane.showMessageDialog( this, "PLEASE ENTER All ","Error", JOptionPane.ERROR_MESSAGE);
            //        if (st.searchstudentfeesAll(idserch.getText(), namesearch.getText(), String.valueOf(m), year)){
                //       st.StudentFeesConditionAll(jTable1, idserch.getText(), namesearch.getText(), String.valueOf(m), year);
                //
                //return;}else {
                //
                //    JOptionPane.showMessageDialog(null, "NOT FOUND","STUDENT",JOptionPane.INFORMATION_MESSAGE);
                //        stu.StudentRecordfees(jTable1);
                // return;
                //        }
            //          }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void addbtn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbtn2MouseClicked

        //         StudentFeesChallan std=new StudentFeesChallan();
        //        boolean isIntegerid=std.isInteger(idserch.getText());
        Student std=new Student();
        //        boolean isIntegerid=std.isInteger(idserch.getText());
        //        String monthse=(String)this.monthsea.getSelectedItem();
        //        String year=(String)this.yearsearch.getSelectedItem();
        //
        if (idnotf1.getText().equals("")&&clas.getText().equals("")&&sec.getText().equals("")){
            JOptionPane.showMessageDialog( this, "PLEASE ENTER All ","Error", JOptionPane.ERROR_MESSAGE);
            std.StudentRecord(jTable1);

            return;
        }
        //
        //        Staff st=new Staff();
        //        int m=0;
        //        m=st.getMonthInt(m,monthse);
        if (idnotf1.getText()!="" &&clas.getText().equals("")&&sec.getText().equals("")){
            if (std.searchStudentid(idnotf1.getText())){
                std.getDataStudentID(jTable1, idnotf1.getText());
                return;
            }
            else {
                JOptionPane.showMessageDialog(null, "NOT FOUND ","STUDENT",JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        }
        if (idnotf1.getText().equals("") && clas.getText()!="" &&sec.getText().equals("")){
            if (std.searchStudentclass(clas.getText())){
                std.getDataStudentclass(jTable1, clas.getText());
                return;
            }
            else {
                JOptionPane.showMessageDialog(null, "NOT FOUND ","STUDENT",JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        }
        if (idnotf1.getText().equals("") && clas.getText().equals("") &&sec.getText()!=""){
            if (std.searchStudentsec(sec.getText())){
                std.getDataStudentSec(jTable1, sec.getText());
                return;
            }
            else {
                JOptionPane.showMessageDialog(null, "NOT FOUND ","STUDENT",JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        }
        if (idnotf1.getText()!="" && clas.getText().equals("") &&sec.getText()!=""){
            if (std.searchStudentidsection(idnotf1.getText(),sec.getText())){
                std.getDataStudentidsec(jTable1, idnotf1.getText(),sec.getText());
                return;
            }
            else {
                JOptionPane.showMessageDialog(null, "NOT FOUND ","STUDENT",JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        }
        if (idnotf1.getText()!="" && clas.getText()!="" &&sec.getText().equals("")){
            if (std.searchStudentidclass(idnotf1.getText(),clas.getText())){
                std.getDataStudentidclass(jTable1, idnotf1.getText(),clas.getText());
                return;
            }
            else {
                JOptionPane.showMessageDialog(null, "NOT FOUND ","STUDENT",JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        }
        if (idnotf1.getText().equals("") && clas.getText()!="" &&sec.getText()!= ""){
            if (std.searchStudentclasssection(clas.getText(),sec.getText())){
                std.getDataStudentclasssec(jTable1, clas.getText(),sec.getText());
                return;
            }
            else {
                JOptionPane.showMessageDialog(null, "NOT FOUND ","STUDENT",JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        }
        if (idnotf1.getText()!="" && clas.getText()!="" &&sec.getText()!= ""){
            if (std.searchStudentidclasssec(idnotf1.getText(),clas.getText(),sec.getText())){
                std.getDataStudentidclasssection(jTable1,idnotf1.getText(), clas.getText(),sec.getText());
                return;
            }
            else {
                JOptionPane.showMessageDialog(null, "NOT FOUND ","STUDENT",JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        }
    }//GEN-LAST:event_addbtn2MouseClicked

    private void idnotf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idnotf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idnotf1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:

        ResultSet rs1=null;
        ResultSet rs=null;
        PreparedStatement pst;
        PreparedStatement pst1;
        try{
            Staff st=new Staff();
            //Connection con=connection.setConnection();
            int row= jTable1.getSelectedRow();
            String idclick= jTable1.getModel().getValueAt(row, 0).toString();
            String nameclick=jTable1.getModel().getValueAt(row, 2).toString();
            id.setText(idclick);
            name.setText(nameclick);
        }catch(Exception e){
            System.out.println(e);
        }
        admissionChallan adm=new admissionChallan();
        adm.c(jTable1);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        childPanel=new adminHomePanel();
        childPanel.setSize(this.getSize());
        this.removeAll();
        this.repaint();
        this.add(childPanel);
        this.validate();
    }//GEN-LAST:event_jPanel2MouseClicked

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void addbtn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbtn3MouseClicked
        // TODO add your handling code here:
        childPanel=new adchalllllanDesire();
        childPanel.setSize(this.getSize());
        this.removeAll();
        this.repaint();
        this.add(childPanel);
        this.validate();
    }//GEN-LAST:event_addbtn3MouseClicked

    private void clasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clasActionPerformed

    private void clasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clasKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_clasKeyTyped

    private void secActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secActionPerformed

    private void secKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_secKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_secKeyTyped

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addbtn2;
    private javax.swing.JPanel addbtn3;
    private javax.swing.JTextField clas;
    private javax.swing.JTextField id;
    private javax.swing.JTextField idnotf1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator30;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField sec;
    // End of variables declaration//GEN-END:variables
}
