/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import code.Connection2DB;
import code.classes;
import code.Student;
//import static code.student.isInteger;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import code.Finance;
import code.admissionChallan;
/**
 *
 * @author Mithrandir
 */
public class addStudent extends javax.swing.JPanel {

    /**
     * Creates new form addStudent
     */JPanel childPanel;
     DateFormat dateFormat =new SimpleDateFormat("MM/dd/YYYY");
     Date date=new Date();
     classes clas=new classes();
     Finance finance=new Finance();
//   Student stud=new Student(IDNUM, challan));
    public addStudent() {
        initComponents();
        clas.Fillcombo(classtf1, sectf1);
        addmidatetf1.setText(" "+dateFormat.format(date));
        
     Student stud;
         stud = new Student(IDNUM, challan);
feeREGtf2.setText("0");
Stationary.setText("0");
anualCh.setText("0");
feetf1.setText("0");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator22 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        NAMETF1 = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        gnametf1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        contact1 = new javax.swing.JTextField();
        jSeparator26 = new javax.swing.JSeparator();
        jSeparator27 = new javax.swing.JSeparator();
        jSeparator28 = new javax.swing.JSeparator();
        contact2 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jSeparator29 = new javax.swing.JSeparator();
        contact3 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        feetf1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jSeparator31 = new javax.swing.JSeparator();
        jLabel38 = new javax.swing.JLabel();
        jSeparator32 = new javax.swing.JSeparator();
        addbutn1 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jSeparator33 = new javax.swing.JSeparator();
        jLabel40 = new javax.swing.JLabel();
        jSeparator34 = new javax.swing.JSeparator();
        classtf1 = new javax.swing.JComboBox<>();
        sectf1 = new javax.swing.JComboBox<>();
        addmidatetf1 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        IDNUM = new javax.swing.JTextField();
        jSeparator35 = new javax.swing.JSeparator();
        challan = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        feeREGtf2 = new javax.swing.JTextField();
        jSeparator36 = new javax.swing.JSeparator();
        jLabel43 = new javax.swing.JLabel();
        anualCh = new javax.swing.JTextField();
        jSeparator37 = new javax.swing.JSeparator();
        jLabel44 = new javax.swing.JLabel();
        Stationary = new javax.swing.JTextField();
        jSeparator38 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1082, 779));

        jLabel25.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setText("GRADE");

        jLabel26.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setText("NAME");

        jLabel27.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 51, 51));
        jLabel27.setText("SECTION");

        NAMETF1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        NAMETF1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        gnametf1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        gnametf1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        gnametf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gnametf1ActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setText("GUARDIAN'S NAME");

        jLabel30.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 51, 51));
        jLabel30.setText("CONTACT NO.1");

        contact1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        contact1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jSeparator27.setOrientation(javax.swing.SwingConstants.VERTICAL);

        contact2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        contact2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel31.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 51, 51));
        jLabel31.setText("CONTACT NO.2");

        contact3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        contact3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel32.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(51, 51, 51));
        jLabel32.setText("CONTACT NO.3");

        jLabel33.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel33.setText("PERSONAL INFORMATION");

        jLabel34.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel34.setText("ACADEMIC INFORMATION");

        jLabel35.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(51, 51, 51));
        jLabel35.setText("FEE");

        feetf1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        feetf1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        feetf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feetf1ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel36.setText("ADD STUDENTS");

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/icons8-back-48.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel37)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel38.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(51, 51, 51));
        jLabel38.setText("ADDMISSION DATE");

        addbutn1.setBackground(new java.awt.Color(51, 153, 255));
        addbutn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addbutn1MouseClicked(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("ADD");

        javax.swing.GroupLayout addbutn1Layout = new javax.swing.GroupLayout(addbutn1);
        addbutn1.setLayout(addbutn1Layout);
        addbutn1Layout.setHorizontalGroup(
            addbutn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addbutn1Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel39)
                .addContainerGap(169, Short.MAX_VALUE))
        );
        addbutn1Layout.setVerticalGroup(
            addbutn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addbutn1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel39)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel40.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(51, 51, 51));
        jLabel40.setText("CHALLAN NO.");

        classtf1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        classtf1.setAutoscrolls(true);
        classtf1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        classtf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classtf1ActionPerformed(evt);
            }
        });

        sectf1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        sectf1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        addmidatetf1.setEditable(false);
        addmidatetf1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        addmidatetf1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addmidatetf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmidatetf1ActionPerformed(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(51, 51, 51));
        jLabel41.setText("ID NUMBER");

        IDNUM.setEditable(false);
        IDNUM.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        IDNUM.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        challan.setEditable(false);
        challan.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        challan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel42.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(51, 51, 51));
        jLabel42.setText("REGISTRATION FEE");

        feeREGtf2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        feeREGtf2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        feeREGtf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feeREGtf2ActionPerformed(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(51, 51, 51));
        jLabel43.setText("ANNUAL CHARGES");

        anualCh.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        anualCh.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        anualCh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anualChActionPerformed(evt);
            }
        });

        jLabel44.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(51, 51, 51));
        jLabel44.setText("STATIONARY FEES");

        Stationary.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Stationary.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Stationary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StationaryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addmidatetf1)
                                    .addComponent(jSeparator32)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel26)
                                                .addComponent(jLabel29)
                                                .addComponent(gnametf1)
                                                .addComponent(NAMETF1)
                                                .addComponent(jLabel30)
                                                .addComponent(jSeparator26)
                                                .addComponent(contact1)
                                                .addComponent(jLabel31)
                                                .addComponent(jSeparator28)
                                                .addComponent(contact2)
                                                .addComponent(jLabel32)
                                                .addComponent(jSeparator29)
                                                .addComponent(contact3)
                                                .addComponent(jSeparator10)
                                                .addComponent(jSeparator33, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
                                            .addComponent(jLabel38))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(104, 104, 104)
                                .addComponent(jSeparator27, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel33)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel41)
                            .addComponent(jSeparator35)
                            .addComponent(IDNUM, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator22, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel27)
                    .addComponent(jLabel25)
                    .addComponent(jLabel40)
                    .addComponent(jLabel35)
                    .addComponent(jSeparator31)
                    .addComponent(feetf1)
                    .addComponent(jSeparator34)
                    .addComponent(classtf1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sectf1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(challan, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(feeREGtf2)
                    .addComponent(jSeparator36)
                    .addComponent(anualCh)
                    .addComponent(jSeparator37)
                    .addComponent(Stationary)
                    .addComponent(jSeparator38)
                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43)
                    .addComponent(jLabel42))
                .addGap(105, 105, 105))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addbutn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(316, 316, 316))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator22, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(classtf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sectf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel40)
                        .addGap(2, 2, 2)
                        .addComponent(challan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator34, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(feetf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator31, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel44)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Stationary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator38, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(feeREGtf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator36, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel43)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(anualCh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator37, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IDNUM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator35, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NAMETF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gnametf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator33, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contact1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator26, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contact2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator28, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contact3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator29, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addmidatetf1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator32, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator27, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(addbutn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void gnametf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gnametf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gnametf1ActionPerformed
Connection2DB connection=new Connection2DB();
        Connection con = connection.setConnection();
        ResultSet rs = null;
        PreparedStatement pst = null;
         
    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        childPanel=new adminHomePanel();
        childPanel.setSize(this.getSize()); 
        this.removeAll();
        this.repaint();
        this.add(childPanel);
        this.validate();
    }//GEN-LAST:event_jPanel4MouseClicked

    private void addbutn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbutn1MouseClicked
     ///   finance.setregistrationFee(Integer.parseInt(IDNUM.getText()),88);
        Student std=new Student();
        boolean isContact1=std.isInteger(contact1.getText());
        boolean isContact2=std.isInteger(contact2.getText());
        boolean isContact3=std.isInteger(contact3.getText());
        boolean fees=std.isInteger(feetf1.getText());
        
        boolean cha=std.isInteger(challan.getText());
        if (IDNUM.getText().equals("")){
            JOptionPane.showMessageDialog( this, "PLEASE ENTER ID NUMBER","Error", JOptionPane.ERROR_MESSAGE);
           return;
        }
        if (NAMETF1.getText().equals("")){
            JOptionPane.showMessageDialog( this, "PLEASE ENTER NAME","Error", JOptionPane.ERROR_MESSAGE);
           return;
        }
        if (gnametf1.getText().equals("")){
            JOptionPane.showMessageDialog( this, "PLEASE ENTER GUARDIAN'S NAME","Error", JOptionPane.ERROR_MESSAGE);
           return;
        }
        if (contact1.getText().equals("")){
            JOptionPane.showMessageDialog( this, "PLEASE ENTER CONTACT NUMBER","Error", JOptionPane.ERROR_MESSAGE);
           return;
        }
        if (challan.getText().equals("")){
            JOptionPane.showMessageDialog( this, "PLEASE ENTER CHALLAN NUMBER","Error", JOptionPane.ERROR_MESSAGE);
           return;
        }
        if (feetf1.getText().equals("")){
            JOptionPane.showMessageDialog( this, "PLEASE ENTER FEES","Error", JOptionPane.ERROR_MESSAGE);
           return;
        }
        if (addmidatetf1.getText().equals("")){
            JOptionPane.showMessageDialog( this, "PLEASE ENTER ADDMISSION DATE","Error", JOptionPane.ERROR_MESSAGE);
           return;
        }
        if (isContact1==false){
            JOptionPane.showMessageDialog( this, "YOU ENTERED CONTACT IN ALPHABETS","Error", JOptionPane.ERROR_MESSAGE);
           return;
        }
        if (fees==false){
            JOptionPane.showMessageDialog( this, "YOU ENTERED FEES IN ALPHABET","Error", JOptionPane.ERROR_MESSAGE);
           return;
        }
        String Class=(String)this.classtf1.getSelectedItem();
        String Section=(String)this.sectf1.getSelectedItem();
        
        Student student=new Student(NAMETF1.getText(), gnametf1.getText(),contact1.getText(),contact2.getText(), contact3.getText(), Integer.parseInt(feetf1.getText()),Class , Section, addmidatetf1.getText(),Integer.parseInt(IDNUM.getText()),Integer.parseInt(challan.getText()));
//       student.setId(Integer.parseInt(IDNUM.getText()));
//       student.setChallanNo(Integer.parseInt(challan.getText()));
        student.addStudent(Stationary.getText());
        student.addStudenttoTask(anualCh.getText());
        student.inputFinance(NAMETF1.getText(), IDNUM.getText(), feetf1.getText(), feeREGtf2.getText(),Stationary.getText());
        finance.setregistrationFee(Integer.parseInt(IDNUM.getText()), Integer.parseInt(feeREGtf2.getText()));
        finance.updateDuesStudentFinance(IDNUM.getText(),finance.generateDues(IDNUM.getText()));
//        idnotf1.setText("");
        NAMETF1.setText("");
        gnametf1.setText("");
        contact1.setText("");
        contact2.setText("");
        contact3.setText("");
        feeREGtf2.setText("");
        feeREGtf2.setText("0");
        Stationary.setText("0");
        anualCh.setText("0");
        feetf1.setText("0");
//        classtf1.setText("");
//        sectf1.setText("");
//        addmidatetf1.setText("");
//        contact3.setText("");
        feetf1.setText("");
        Student st=new Student();
    //    st.studentTotask(IDNUM.getText(), NAMETF1.getText(), "1", "1", "1");
        student.countID(IDNUM, challan);
       childPanel=new addmissionChallan();
        childPanel.setSize(this.getSize()); 
        this.removeAll();
        this.repaint();
        this.add(childPanel);
        this.validate();
    }//GEN-LAST:event_addbutn1MouseClicked

    private void addmidatetf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmidatetf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addmidatetf1ActionPerformed

    private void classtf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classtf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classtf1ActionPerformed

    private void feetf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feetf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_feetf1ActionPerformed

    private void feeREGtf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feeREGtf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_feeREGtf2ActionPerformed

    private void anualChActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anualChActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anualChActionPerformed

    private void StationaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StationaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StationaryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDNUM;
    private javax.swing.JTextField NAMETF1;
    private javax.swing.JTextField Stationary;
    private javax.swing.JPanel addbutn1;
    private javax.swing.JTextField addmidatetf1;
    private javax.swing.JTextField anualCh;
    private javax.swing.JTextField challan;
    private javax.swing.JComboBox<String> classtf1;
    private javax.swing.JTextField contact1;
    private javax.swing.JTextField contact2;
    private javax.swing.JTextField contact3;
    private javax.swing.JTextField feeREGtf2;
    private javax.swing.JTextField feetf1;
    private javax.swing.JTextField gnametf1;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator31;
    private javax.swing.JSeparator jSeparator32;
    private javax.swing.JSeparator jSeparator33;
    private javax.swing.JSeparator jSeparator34;
    private javax.swing.JSeparator jSeparator35;
    private javax.swing.JSeparator jSeparator36;
    private javax.swing.JSeparator jSeparator37;
    private javax.swing.JSeparator jSeparator38;
    private javax.swing.JComboBox<String> sectf1;
    // End of variables declaration//GEN-END:variables
}
