/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import code.Staff;
import static code.Student.isInteger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Mithrandir
 */
public class AdminStaff extends javax.swing.JPanel {

    /**
     * Creates new form AdminStaff
     */JPanel childPanel;
     Staff staf=new Staff();
//     Staff st=new Staff(id)
    public AdminStaff() {
        initComponents();
        staf.STAFFRecord(jTable1);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        idnotf1 = new javax.swing.JTextField();
        jSeparator25 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        designation = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        DATE = new javax.swing.JTextField();
        jSeparator33 = new javax.swing.JSeparator();
        jSeparator26 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        NAMETF1 = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel40 = new javax.swing.JLabel();
        jSeparator34 = new javax.swing.JSeparator();
        jSeparator28 = new javax.swing.JSeparator();
        salary = new javax.swing.JFormattedTextField();
        contact = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel32 = new javax.swing.JLabel();
        nameSearch = new javax.swing.JTextField();
        jSeparator27 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1082, 779));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel36.setText("STAFF");

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/icons8-back-48.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel37)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel28.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 51));
        jLabel28.setText("ENTER ID TO SEARCH");

        idnotf1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        idnotf1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        idnotf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idnotf1ActionPerformed(evt);
            }
        });
        idnotf1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idnotf1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idnotf1KeyTyped(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/icons8-search-40.png"))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/icons8-edit-40.png"))); // NOI18N
        jLabel5.setText("EDIT ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(51, 153, 255));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel5MouseReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/icons8-trash-40.png"))); // NOI18N
        jLabel6.setText("DELETE ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionBackground(new java.awt.Color(51, 153, 255));
        jTable1.setShowHorizontalLines(false);
        jTable1.setShowVerticalLines(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel31.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 51, 51));
        jLabel31.setText("CONTACT");

        jLabel33.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel33.setText("SELECTED PERSON INFORMATION");

        designation.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        designation.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        designation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                designationActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setText("DESIGNATION");

        jLabel30.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 51, 51));
        jLabel30.setText("DATE OF JOINING");

        DATE.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        DATE.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel26.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setText("NAME");

        NAMETF1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        NAMETF1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel40.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(51, 51, 51));
        jLabel40.setText("SALARY");

        salary.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        salary.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        salary.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        contact.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        contact.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel32.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(51, 51, 51));
        jLabel32.setText("ENTER NAME TO SEARCH");

        nameSearch.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        nameSearch.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        nameSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameSearchActionPerformed(evt);
            }
        });
        nameSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameSearchKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameSearchKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel28)
                            .addComponent(jSeparator25)
                            .addComponent(idnotf1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel32)
                            .addComponent(jSeparator27)
                            .addComponent(nameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel33)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel29)
                                    .addComponent(designation)
                                    .addComponent(NAMETF1)
                                    .addComponent(jLabel30)
                                    .addComponent(jSeparator26)
                                    .addComponent(DATE)
                                    .addComponent(jLabel31)
                                    .addComponent(jSeparator28)
                                    .addComponent(contact)
                                    .addComponent(jSeparator10)
                                    .addComponent(jSeparator33)
                                    .addComponent(jLabel40)
                                    .addComponent(jSeparator34)
                                    .addComponent(salary, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(7, 7, 7)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idnotf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator25, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator27, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NAMETF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(designation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator33, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator26, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator28, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salary, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator34, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        childPanel=new Staffhome();
        childPanel.setSize(this.getSize());
        this.removeAll();
        this.repaint();
        this.add(childPanel);
        this.validate();
    }//GEN-LAST:event_jPanel4MouseClicked

    private void idnotf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idnotf1ActionPerformed
        // TODO add your handling code here:
         if (idnotf1.getText().equals("")){
            return;
      
        }
    Staff staf=new Staff();
            if (idnotf1.getText()!=""&&nameSearch.getText().equals("")){
                if (staf.searchEmployee(idnotf1.getText())){
                staf.getDataStaffID1(jTable1, idnotf1.getText());
                return;
                }
                else {
                      JOptionPane.showMessageDialog(null, "NOT FOUND","STAFF",JOptionPane.INFORMATION_MESSAGE);
 return;
                }
            }
            if (nameSearch.getText()!=""&&idnotf1.getText().equals("")){
                if (staf.searchEmployeename(nameSearch.getText())){
                    staf.getDataStaffNAME(jTable1, nameSearch.getText());
                return;}
                else {
                      JOptionPane.showMessageDialog(null, "NOT FOUND","STAFF",JOptionPane.INFORMATION_MESSAGE);
 return;
                }
            }
            if (idnotf1.getText()!=""&&nameSearch.getText()!=""){
                if (staf.searchEmployeenameid(nameSearch.getText(), idnotf1.getText())){
                staf.getDataStaff(jTable1, idnotf1.getText(),nameSearch.getText());
                return;
                }
                else {
                      JOptionPane.showMessageDialog(null, "NOT FOUND","STAFF",JOptionPane.INFORMATION_MESSAGE);
 return;
                }
            }
          
//    staf.getDataStaff(jTable1, idnotf1.getText(),nameSearch.getText());

    }//GEN-LAST:event_idnotf1ActionPerformed

    private void idnotf1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idnotf1KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_idnotf1KeyPressed

    private void idnotf1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idnotf1KeyTyped
        // TODO add your handling code here:
         if(idnotf1.getText().equals(""))
        {
            staf.STAFFRecord(jTable1);
        }
           
    }//GEN-LAST:event_idnotf1KeyTyped

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
       boolean isIntegersalary=isInteger(salary.getText());
            
         boolean isIntegercontact=isInteger(contact.getText());
       try{
       
         if (NAMETF1.getText().equals("")){
                 JOptionPane.showMessageDialog( this, "PLEASE ENTER NAME ","Error", JOptionPane.ERROR_MESSAGE);
        return;
             }
              
              if (contact.getText().equals("")){
                 JOptionPane.showMessageDialog( this, "PLEASE ENTER CONTACT","Error", JOptionPane.ERROR_MESSAGE);
          return;
             }
              if (DATE.getText().equals("")){
                 JOptionPane.showMessageDialog( this, "PLEASE ENTER DATE","Error", JOptionPane.ERROR_MESSAGE);
          return;
             }
              
              if (salary.getText().equals("")){
                  JOptionPane.showMessageDialog( this, "PLEASE ENTER SALARY","Error", JOptionPane.ERROR_MESSAGE);
             return;}

              if (designation.equals("")){
                   JOptionPane.showMessageDialog( this, "PLEASE ENTER DESIGNATION","Error", JOptionPane.ERROR_MESSAGE);
             return;
              }
              
              
              if (isIntegersalary==false){
                  
                 JOptionPane.showMessageDialog( this, "YOU ENTERED SALART IN ALPHABET ","Error", JOptionPane.ERROR_MESSAGE);
        return;
             }
             
              if (isIntegercontact==false){
                 JOptionPane.showMessageDialog( this, "YOU ENTERED CONTACT NUMBER IN ALPHABET ","Error", JOptionPane.ERROR_MESSAGE);
        return;
             }
              if(isIntegersalary==false&&isIntegercontact==false){
                 JOptionPane.showMessageDialog( this, "YOU ENTERED CONTACT NUMBER,ID NUMBER AND SALRY IN ALPHABET ","Error", JOptionPane.ERROR_MESSAGE);
        return;
              }
              
            Staff staff=new Staff( NAMETF1.getText(), designation.getText(), contact.getText(), DATE.getText(), Integer.parseInt(salary.getText()));
            staff.updateStaff(idnotf1.getText());
            NAMETF1.setText("");
            contact.setText("");
            salary.setText("");
            designation.setText("");
            DATE.setText("");
       }catch(Exception e){
           JOptionPane.showMessageDialog( this, "ERROR IN ENROLL STAFF","Error", JOptionPane.ERROR_MESSAGE);
           
       }
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        if (NAMETF1.getText().equals("")){
                 JOptionPane.showMessageDialog( this, "PLEASE ENTER NAME ","Error", JOptionPane.ERROR_MESSAGE);
        return;
             }
        if (idnotf1.getText().equals("")){
                 JOptionPane.showMessageDialog( this, "PLEASE ENTER NAME ","Error", JOptionPane.ERROR_MESSAGE);
        return;
             }
        Staff sta=new Staff();
        sta.deleteStaff(idnotf1.getText());
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed

        //classes.ClassesRecord(jTable1);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MousePressed

    private void jPanel5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseReleased
        // TODO add your handling code here:
        //classes.ClassesRecord(jTable1);
    }//GEN-LAST:event_jPanel5MouseReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
     Staff staf=new Staff();
     staf.staffClickTable(jTable1, NAMETF1, designation, contact, salary, idnotf1, DATE);
    }//GEN-LAST:event_jTable1MouseClicked

    private void designationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_designationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_designationActionPerformed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
        staf.STAFFRecord(jTable1);
    }//GEN-LAST:event_formMouseMoved

    private void nameSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameSearchActionPerformed
        // TODO add your handling code here:
                 if (nameSearch.getText().equals("")){
            return;
      
        }
                  if (idnotf1.getText()!=""&&nameSearch.getText().equals("")){
                if (staf.searchEmployee(idnotf1.getText())){
                staf.getDataStaffID1(jTable1, idnotf1.getText());
                return;
                }
                else {
                      JOptionPane.showMessageDialog(null, "NOT FOUND","STAFF",JOptionPane.INFORMATION_MESSAGE); return;
                }
            }
            if (nameSearch.getText()!=""&&idnotf1.getText().equals("")){
                if (staf.searchEmployeename(nameSearch.getText())){
                    staf.getDataStaffNAME(jTable1, nameSearch.getText());
                return;
                }
                else {
                      JOptionPane.showMessageDialog(null, "NOT FOUND","STAFF",JOptionPane.INFORMATION_MESSAGE);
 return;
                }
            }
            if (idnotf1.getText()!=""&&nameSearch.getText()!=""){
                if (staf.searchEmployeenameid(nameSearch.getText(), idnotf1.getText())){
                staf.getDataStaff(jTable1, idnotf1.getText(),nameSearch.getText());
                return;
                }
                else {
                      JOptionPane.showMessageDialog(null, "NOT FOUND","STAFF",JOptionPane.INFORMATION_MESSAGE);
 return;
                }
            }
    Staff staf=new Staff();
//    staf.getDataStaff(jTable1, idnotf1.getText(),nameSearch.getText());

    }//GEN-LAST:event_nameSearchActionPerformed

    private void nameSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameSearchKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameSearchKeyPressed

    private void nameSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameSearchKeyTyped
        // TODO add your handling code here:
        if (nameSearch.getText().equals("")){
            staf.STAFFRecord(jTable1);
        }
    }//GEN-LAST:event_nameSearchKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DATE;
    private javax.swing.JTextField NAMETF1;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField designation;
    private javax.swing.JTextField idnotf1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator33;
    private javax.swing.JSeparator jSeparator34;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nameSearch;
    private javax.swing.JFormattedTextField salary;
    // End of variables declaration//GEN-END:variables
}
