/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import javax.swing.JPanel;
import code.Student;
import code.Finance;
import code.Staff;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author Mithrandir
 */
public class EDITFEEPANEL extends javax.swing.JPanel {

    /**
     * Creates new form EDITFEEPANEL
     */JPanel childPanel;
     Student student=new Student();
     Finance f=new Finance();
    public EDITFEEPANEL() {
        initComponents();
        student.StudentRecordfees(jTable1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        NAMETF1 = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        regtxt = new javax.swing.JTextField();
        jSeparator33 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        narytxt = new javax.swing.JTextField();
        jSeparator26 = new javax.swing.JSeparator();
        jLabel31 = new javax.swing.JLabel();
        anualtxt = new javax.swing.JTextField();
        jSeparator28 = new javax.swing.JSeparator();
        jLabel32 = new javax.swing.JLabel();
        feetxt = new javax.swing.JTextField();
        jSeparator29 = new javax.swing.JSeparator();
        jLabel33 = new javax.swing.JLabel();
        distxt = new javax.swing.JTextField();
        jSeparator30 = new javax.swing.JSeparator();
        duestxt = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jSeparator31 = new javax.swing.JSeparator();
        addbutn1 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        idserch = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        yearsearch = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        monthsea = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        addbtn = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1082, 779));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/icons8-back-48.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setText("MANAGE FEE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel26.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setText("NAME");

        NAMETF1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        NAMETF1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel29.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setText("REGISTRATION FEE");

        regtxt.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        regtxt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        regtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regtxtActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 51, 51));
        jLabel30.setText("STATIONARY FEE");

        narytxt.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        narytxt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel31.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 51, 51));
        jLabel31.setText("ANNUAL FEE");

        anualtxt.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        anualtxt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel32.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(51, 51, 51));
        jLabel32.setText("TUITION FEE");

        feetxt.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        feetxt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel33.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(51, 51, 51));
        jLabel33.setText("DISCOUNT");

        distxt.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        distxt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        distxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distxtActionPerformed(evt);
            }
        });

        duestxt.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        duestxt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel34.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(51, 51, 51));
        jLabel34.setText("DUES");

        addbutn1.setBackground(new java.awt.Color(51, 153, 255));
        addbutn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addbutn1MouseClicked(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("EDIT");

        javax.swing.GroupLayout addbutn1Layout = new javax.swing.GroupLayout(addbutn1);
        addbutn1.setLayout(addbutn1Layout);
        addbutn1Layout.setHorizontalGroup(
            addbutn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addbutn1Layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addComponent(jLabel39)
                .addGap(85, 85, 85))
        );
        addbutn1Layout.setVerticalGroup(
            addbutn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addbutn1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel39)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel27.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 51, 51));
        jLabel27.setText("ID");

        idserch.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        idserch.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        yearsearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1982", "1981", "1980" }));
        yearsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearsearchActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 51));
        jLabel28.setText("MONTH");

        monthsea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "JANUARY", "FEBUEARY", "MARCH", "APRIL", "MAY", "JUNE", "JULY", "AUGUST", "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER" }));
        monthsea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthseaActionPerformed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(51, 51, 51));
        jLabel35.setText("YEAR");

        addbtn.setBackground(new java.awt.Color(51, 153, 255));
        addbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addbtnMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/icons8-search-40.png"))); // NOI18N
        jLabel4.setText("SEARCH");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout addbtnLayout = new javax.swing.GroupLayout(addbtn);
        addbtn.setLayout(addbtnLayout);
        addbtnLayout.setHorizontalGroup(
            addbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addbtnLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        addbtnLayout.setVerticalGroup(
            addbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addbtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(144, 144, 144)
                                        .addComponent(regtxt))
                                    .addComponent(NAMETF1)
                                    .addComponent(jSeparator26)
                                    .addComponent(narytxt)
                                    .addComponent(jSeparator28)
                                    .addComponent(anualtxt)
                                    .addComponent(jSeparator10)
                                    .addComponent(jSeparator29)
                                    .addComponent(feetxt)
                                    .addComponent(jSeparator30)
                                    .addComponent(distxt)
                                    .addComponent(jSeparator31)
                                    .addComponent(duestxt)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel26)
                                            .addComponent(jLabel30)
                                            .addComponent(jLabel31)
                                            .addComponent(jSeparator33, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel32)
                                            .addComponent(jLabel33)
                                            .addComponent(jLabel34)
                                            .addComponent(jLabel29))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(76, 76, 76))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(addbutn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator11, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(idserch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel28))
                            .addComponent(monthsea, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel35))
                            .addComponent(yearsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idserch, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel28))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(yearsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.LEADING))
                        .addComponent(monthsea, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NAMETF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29)
                        .addGap(2, 2, 2)
                        .addComponent(regtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator33, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(narytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator26, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(anualtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator28, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(feetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator29, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(duestxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator31, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(distxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator30, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addbutn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        childPanel=new adminHomePanel();
        childPanel.setSize(this.getSize());
        this.removeAll();
        this.repaint();
        this.add(childPanel);
        this.validate();
    }//GEN-LAST:event_jPanel1MouseClicked

    private void regtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regtxtActionPerformed

    private void addbutn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbutn1MouseClicked
        ///   finance.setregistrationFee(Integer.parseInt(IDNUM.getText()),88);
      Finance f=new Finance();
      f.checkdues(jTable1, duestxt, distxt);
student.StudentRecordfees(jTable1);
    }//GEN-LAST:event_addbutn1MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
       student.clickTable(jTable1, idserch, NAMETF1, regtxt, narytxt, anualtxt, feetxt, distxt, duestxt);
    }//GEN-LAST:event_jTable1MouseClicked

    private void distxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distxtActionPerformed
        // TODO add your handling code here:
        f.disss(duestxt, Integer.valueOf(duestxt.getText()), Integer.valueOf(distxt.getText()));
    }//GEN-LAST:event_distxtActionPerformed

    private void yearsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearsearchActionPerformed

    private void monthseaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthseaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthseaActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void addbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbtnMouseClicked

        Student std=new Student();
        //        boolean isIntegerid=std.isInteger(idserch.getText());
        String monthse=(String)this.monthsea.getSelectedItem();
        String year=(String)this.yearsearch.getSelectedItem();

        if (idserch.getText().equals("")&&monthse.equals(" ")&&year.equals(" ")){
//            JOptionPane.showMessageDialog( this, "PLEASE ENTER All ","Error", JOptionPane.ERROR_MESSAGE);
             student.StudentRecordfees(jTable1);
   
            return;
        }

        Staff st=new Staff();
        int m=0;
        m=st.getMonthInt(m,monthse);
        //        if (id)
        if (idserch.getText()!=""&&monthse.equals(" ")&&year.equals(" ")){
            if (std.searchStudentfeesid(idserch.getText())){
                std.StudentRecordfeesid(jTable1, idserch.getText());
                return;
            }
            else {
                JOptionPane.showMessageDialog(null, "NOT FOUND ","STAFF",JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        }
//        if (idserch.getText().equals("")&&namesearch.getText()!=""&&monthse.equals(" ")&&year.equals(" ")){
//            if (st.searchStaffname( namesearch.getText()))  {
//                st.staffReportConditionname(jTable1, namesearch.getText());//jTable1);
//            return;}
//        else {
//            JOptionPane.showMessageDialog(null, "NOT FOUND ","STAFF",JOptionPane.INFORMATION_MESSAGE);
//            return;
//        }
//        }
        if (idserch.getText().equals("")&&monthse!=" "&&year.equals(" ")){
            //              JOptionPane.showMessageDialog( this, "PLEASE ENTER All ","Error", JOptionPane.ERROR_MESSAGE);
            if (std.searchStudentfeesmonth(String.valueOf(m)))     {
                std.StudentRecordfeesmonth(jTable1, String.valueOf(m));
                return;
            }
            else {
                JOptionPane.showMessageDialog(null, "NOT FOUND ","STAFF",JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        }
        if (idserch.getText().equals("")&&monthse.equals(" ")&&year!=" "){
            //              JOptionPane.showMessageDialog( this, "PLEASE ENTER All ","Error", JOptionPane.ERROR_MESSAGE);
            if (std.searchStudentfeesyear(year)){
                std.StudentRecordfeesyear(jTable1, year);
                return;}else {
                JOptionPane.showMessageDialog(null, "NOT FOUND ","STAFF",JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        }
//        if (idserch.getText()!=""&&namesearch.getText()!=""&&monthse.equals(" ")&&year.equals(" ")){
//            //              JOptionPane.showMessageDialog( this, "PLEASE ENTER All ","Error", JOptionPane.ERROR_MESSAGE);
//            if (st.searchStaffidname(idserch.getText(), namesearch.getText())){
//                st.staffReportConditionidName(jTable1, idserch.getText(),namesearch.getText());
//                return;}
//            else {
//                JOptionPane.showMessageDialog(null, "NOT FOUND ","STAFF",JOptionPane.INFORMATION_MESSAGE);
//                return;
//            }
//        }

        if (idserch.getText()!=""&&monthse!=" "&&year.equals(" ")){
            //              JOptionPane.showMessageDialog( this, "PLEASE ENTER All ","Error", JOptionPane.ERROR_MESSAGE);
            if (std.searchStudentfeesidmonth(idserch.getText(), String.valueOf(m))){
                std.StudentRecordfeesidmonth(jTable1, idserch.getText(),String.valueOf(m));
                return;}
            else {
                JOptionPane.showMessageDialog(null, "NOT FOUND","STAFF",JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        }

        if (idserch.getText()!=""&&monthse.equals(" ")&&year!=" "){
            //              JOptionPane.showMessageDialog( this, "PLEASE ENTER All ","Error", JOptionPane.ERROR_MESSAGE);
            if (std.searchStudentfeesidyear(idserch.getText(), year)){
                std.StudentRecordfeesidyear(jTable1, idserch.getText(),year);
                return;
            }
            else {
                JOptionPane.showMessageDialog(null, "NOT FOUND","STAFF",JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        }

//        if (idserch.getText().equals("")&&namesearch.getText()!=""&&monthse!=" "&&year.equals(" ")){
//            //              JOptionPane.showMessageDialog( this, "PLEASE ENTER All ","Error", JOptionPane.ERROR_MESSAGE);
//            if (st.searchStaffnamemonth(namesearch.getText(), String.valueOf(m))){
//                st.staffReportConditionNameMonth(jTable1, namesearch.getText(),String.valueOf(m));
//                return;}
//            else {
//                JOptionPane.showMessageDialog(null, "NOT FOUND  ","STAFF",JOptionPane.INFORMATION_MESSAGE);
//                return;
//            }
//        }
//
//        if (idserch.getText().equals("")&&namesearch.getText()!=""&&monthse.equals(" ")&&year!=" "){
//            //              JOptionPane.showMessageDialog( this, "PLEASE ENTER All ","Error", JOptionPane.ERROR_MESSAGE);
//            if (st.searchStaffnameyear(namesearch.getText(), year)){
//                st.staffReportConditionNameYear(jTable1, namesearch.getText(),year);
//                return;}
//            else {
//                JOptionPane.showMessageDialog(null, "NOT FOUND ","STAFF",JOptionPane.INFORMATION_MESSAGE);
//                return;
//            }
//        }

        if (idserch.getText().equals("")&&monthse!=" "&&year!=" "){
//            System.out.println("hy");
            if (std.searchStudentfeesmonthyear(String.valueOf(m), year)){
//                System.out.println("9809798647836874");
                std.StudentRecordfeesmonthyear(jTable1, String.valueOf(m), year);//Year(jTable1, namesearch.getText(),year);
                return;}
            else {
                JOptionPane.showMessageDialog(null, "NOT FOUND ","STAFF",JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        }

//        if (idserch.getText()!=""&&namesearch.getText()!=""&&monthse!=" "&&year.equals(" ")){
//            //              JOptionPane.showMessageDialog( this, "PLEASE ENTER All ","Error", JOptionPane.ERROR_MESSAGE);
//            if (st.searchStafffidnamemonth(idserch.getText(), namesearch.getText(), String.valueOf(m))){
//                st.staffReportConditionidNameMonth(jTable1, idserch.getText(),namesearch.getText(),String.valueOf(m));
//                return;}else {
//                JOptionPane.showMessageDialog(null, "NOT FOUND ","STAFF",JOptionPane.INFORMATION_MESSAGE);
//                return;
//            }
//        }

        if (idserch.getText()!=""&&monthse!=" "&&year!=" "){
            //              JOptionPane.showMessageDialog( this, "PLEASE ENTER All ","Error", JOptionPane.ERROR_MESSAGE);
            if (std.searchStudentfeesidmonthyear(idserch.getText(), String.valueOf(m), year)){
                std.StudentRecordfeesidmonthyear(jTable1, idserch.getText(),String.valueOf(m),year);
                return;}else {
                JOptionPane.showMessageDialog(null, "NOT FOUND ","STAFF",JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        }

//        if (idserch.getText().equals("")&&namesearch.getText()!=""&&monthse!=" "&&year!=" "){
//            //              JOptionPane.showMessageDialog( this, "PLEASE ENTER All ","Error", JOptionPane.ERROR_MESSAGE);
//            if (st.searchStaffnamemonthyear(namesearch.getText(), String.valueOf(m), year)){
//                st.staffReportConditionNameMonthYear(jTable1, namesearch.getText(),String.valueOf(m),year);
//                return;
//            }else {
//                JOptionPane.showMessageDialog(null, "NOT FOUND ","STAFF",JOptionPane.INFORMATION_MESSAGE);
//                return;
//            }
//        }

        //        if (idserch.getText()!="" && namesearch.getText()!="" && monthse!=" " && year!=" "){
            ////              JOptionPane.showMessageDialog( this, "PLEASE ENTER All ","Error", JOptionPane.ERROR_MESSAGE);
            //            if (st.searchStaffAll(idserch.getText(), namesearch.getText(), String.valueOf(m), year)){
                //       st.staffReportConditionAll(jTable1, idserch.getText(), namesearch.getText(), String.valueOf(m), year);
                //
                //return;}
            //            else {
                //                JOptionPane.showMessageDialog(null, "NOT FOUND id name month year","STAFF",JOptionPane.INFORMATION_MESSAGE);
                // return;
                //            }
            //          }
    }//GEN-LAST:event_addbtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NAMETF1;
    private javax.swing.JPanel addbtn;
    private javax.swing.JPanel addbutn1;
    private javax.swing.JTextField anualtxt;
    private javax.swing.JTextField distxt;
    private javax.swing.JTextField duestxt;
    private javax.swing.JTextField feetxt;
    private javax.swing.JTextField idserch;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator30;
    private javax.swing.JSeparator jSeparator31;
    private javax.swing.JSeparator jSeparator33;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> monthsea;
    private javax.swing.JTextField narytxt;
    private javax.swing.JTextField regtxt;
    private javax.swing.JComboBox<String> yearsearch;
    // End of variables declaration//GEN-END:variables
}
