/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

//import code.Fees;
import code.Staff;
import code.Student;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Mithrandir
 */
public class StaffReport extends javax.swing.JPanel {

    /**
     * Creates new form StaffReport
     */JPanel childPanel;
     public void printComponenet(final Component component){
  PrinterJob pj = PrinterJob.getPrinterJob();
  pj.setJobName(" Print Component ");

  pj.setPrintable (new Printable() {    
    public int print(Graphics pg, PageFormat pf, int pageNum){
      if (pageNum > 0){
      return Printable.NO_SUCH_PAGE;
      }
      Graphics2D g2 = (Graphics2D) pg;
      g2.translate(pf.getImageableX(), pf.getImageableY());
      String name="ID   ";
        System.out.println("");
      jTable1.getColumnName(0);
     component.paint(g2);
      return Printable.PAGE_EXISTS;
    }
  });
  if (pj.printDialog() == false)
  return;

  try {
        pj.print();
  } catch (PrinterException ex) {
        // handle exception
  }
     }
     
    public StaffReport() {
        initComponents();
        Staff staf=new Staff();
        staf.staffReport(jTable1);
//        int h=staf.getMonth();
//        Fees fe=new Fees();
//        String r= fe.getMonthString(h);
//        monthsea.setSelectedItem(r);
//        int q=staf.getYear();
//        yearsearch.setSelectedIndex(q);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        monthsea = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        namesearch = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        idserch = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        yearsearch = new javax.swing.JComboBox<>();
        addbtn = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        printPanel = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel34 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        name = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jSeparator33 = new javax.swing.JSeparator();
        jLabel32 = new javax.swing.JLabel();
        present = new javax.swing.JTextField();
        jSeparator26 = new javax.swing.JSeparator();
        jLabel40 = new javax.swing.JLabel();
        jSeparator34 = new javax.swing.JSeparator();
        jSeparator28 = new javax.swing.JSeparator();
        late = new javax.swing.JFormattedTextField();
        absent = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        PRINTPAnelTAble = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1163, 750));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/icons8-back-48.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setText("STAFF REPORT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        monthsea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "JANUARY", "FEBUEARY", "MARCH", "APRIL", "MAY", "JUNE", "JULY", "AUGUST", "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER" }));
        monthsea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthseaActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setText("NAME");

        namesearch.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        namesearch.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        namesearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namesearchActionPerformed(evt);
            }
        });
        namesearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                namesearchKeyTyped(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 51, 51));
        jLabel27.setText("MONTH");

        jLabel28.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 51));
        jLabel28.setText("ID");

        idserch.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        idserch.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        idserch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idserchActionPerformed(evt);
            }
        });
        idserch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idserchKeyTyped(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setText("YEAR");

        yearsearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1982", "1981", "1980" }));
        yearsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearsearchActionPerformed(evt);
            }
        });

        addbtn.setBackground(new java.awt.Color(51, 153, 255));
        addbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addbtnMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/icons8-search-40.png"))); // NOI18N
        jLabel4.setText("SEARCH");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout addbtnLayout = new javax.swing.GroupLayout(addbtn);
        addbtn.setLayout(addbtnLayout);
        addbtnLayout.setHorizontalGroup(
            addbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addbtnLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        addbtnLayout.setVerticalGroup(
            addbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addbtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/icons8-edit-40.png"))); // NOI18N
        jLabel5.setText("EDIT ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(51, 153, 255));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel5MouseReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/icons8-send-to-printer-40.png"))); // NOI18N
        jLabel6.setText("PRINT");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(51, 153, 255));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel6MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel6MouseReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/icons8-send-to-printer-40.png"))); // NOI18N
        jLabel7.setText("PRINT");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        printPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel33.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel33.setText("SELECTED PERSON INFORMATION");

        jLabel34.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(51, 51, 51));
        jLabel34.setText("ID");

        id.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        id.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        name.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        name.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 51, 51));
        jLabel30.setText("NAME");

        jLabel32.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(51, 51, 51));
        jLabel32.setText("PRESENT");

        present.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        present.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        present.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presentActionPerformed(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(51, 51, 51));
        jLabel40.setText("LATE");

        late.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        late.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        late.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        absent.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        absent.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel31.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 51, 51));
        jLabel31.setText("ABSENT");

        javax.swing.GroupLayout printPanelLayout = new javax.swing.GroupLayout(printPanel);
        printPanel.setLayout(printPanelLayout);
        printPanelLayout.setHorizontalGroup(
            printPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(printPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(printPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel30)
                    .addComponent(jLabel34)
                    .addComponent(jSeparator2)
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                    .addComponent(jSeparator12)
                    .addComponent(id)
                    .addComponent(name)
                    .addComponent(jLabel32)
                    .addComponent(jSeparator33, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(printPanelLayout.createSequentialGroup()
                        .addGroup(printPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel31)
                            .addComponent(absent)
                            .addComponent(jLabel40)
                            .addComponent(late, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator28)
                            .addComponent(jSeparator34))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator26))
                    .addComponent(present, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        printPanelLayout.setVerticalGroup(
            printPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(printPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator33, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32)
                .addGap(1, 1, 1)
                .addComponent(present, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(printPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator26, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(printPanelLayout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(absent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator28, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(late, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator34, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        PRINTPAnelTAble.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionBackground(new java.awt.Color(51, 153, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout PRINTPAnelTAbleLayout = new javax.swing.GroupLayout(PRINTPAnelTAble);
        PRINTPAnelTAble.setLayout(PRINTPAnelTAbleLayout);
        PRINTPAnelTAbleLayout.setHorizontalGroup(
            PRINTPAnelTAbleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        );
        PRINTPAnelTAbleLayout.setVerticalGroup(
            PRINTPAnelTAbleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PRINTPAnelTAbleLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(PRINTPAnelTAble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(printPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(179, 179, 179))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel28)
                            .addComponent(idserch, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(jSeparator11))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator10)
                                .addComponent(namesearch, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jLabel27))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(monthsea, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel29))
                            .addComponent(yearsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel27))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(yearsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel26)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(namesearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(monthsea, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(7, 7, 7)
                            .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idserch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PRINTPAnelTAble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(printPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        childPanel=new Staffhome();
        childPanel.setSize(this.getSize());
        this.removeAll();
        this.repaint();
        this.add(childPanel);
        this.validate();
    }//GEN-LAST:event_jPanel1MouseClicked

    private void addbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbtnMouseClicked

         Student std=new Student();
//        boolean isIntegerid=std.isInteger(idserch.getText());
          String monthse=(String)this.monthsea.getSelectedItem();
          String year=(String)this.yearsearch.getSelectedItem();
      
          if (idserch.getText().equals("")&&namesearch.getText().equals("")&&monthse.equals(" ")&&year.equals(" ")){
              JOptionPane.showMessageDialog( this, "PLEASE ENTER All ","Error", JOptionPane.ERROR_MESSAGE);
          return;
          }
          
       Staff st=new Staff();
       int m=0;
        m=st.getMonthInt(m,monthse);
//        if (id)
        if (idserch.getText()!=""&&namesearch.getText().equals("")&&monthse.equals(" ")&&year.equals(" ")){
if (st.searchStaffid(idserch.getText())){
st.staffReportConditionid(jTable1, idserch.getText());
return;
}
else {
     JOptionPane.showMessageDialog(null, "NOT FOUND ","STAFF",JOptionPane.INFORMATION_MESSAGE);
 return;
}
          }
        if (idserch.getText().equals("")&&namesearch.getText()!=""&&monthse.equals(" ")&&year.equals(" ")){
            if (st.searchStaffname( namesearch.getText()))  {
            st.staffReportConditionname(jTable1, namesearch.getText());//jTable1);
              return;}
            else {
                JOptionPane.showMessageDialog(null, "NOT FOUND ","STAFF",JOptionPane.INFORMATION_MESSAGE);
 return;
            }
          }
        if (idserch.getText().equals("")&&namesearch.getText().equals("")&&monthse!=" "&&year.equals(" ")){
//              JOptionPane.showMessageDialog( this, "PLEASE ENTER All ","Error", JOptionPane.ERROR_MESSAGE);
if (st.searchStaffmonth(String.valueOf(m)))     {      
st.staffReportConditionmonth(jTable1, String.valueOf(m));
return;
}
else {
    JOptionPane.showMessageDialog(null, "NOT FOUND ","STAFF",JOptionPane.INFORMATION_MESSAGE);
 return;
}
          }
        if (idserch.getText().equals("")&&namesearch.getText().equals("")&&monthse.equals(" ")&&year!=" "){
//              JOptionPane.showMessageDialog( this, "PLEASE ENTER All ","Error", JOptionPane.ERROR_MESSAGE);
if (st.searchStaffyear(year)){           
st.staffReportConditionyear(jTable1, year);
return;}else {
    JOptionPane.showMessageDialog(null, "NOT FOUND ","STAFF",JOptionPane.INFORMATION_MESSAGE);
 return;
}
          }
        if (idserch.getText()!=""&&namesearch.getText()!=""&&monthse.equals(" ")&&year.equals(" ")){
//              JOptionPane.showMessageDialog( this, "PLEASE ENTER All ","Error", JOptionPane.ERROR_MESSAGE);
if (st.searchStaffidname(idserch.getText(), namesearch.getText())){
            st.staffReportConditionidName(jTable1, idserch.getText(),namesearch.getText());
return;}
else {
    JOptionPane.showMessageDialog(null, "NOT FOUND ","STAFF",JOptionPane.INFORMATION_MESSAGE);
 return;
}
          }
        
        if (idserch.getText()!=""&&namesearch.getText().equals("")&&monthse!=" "&&year.equals(" ")){
//              JOptionPane.showMessageDialog( this, "PLEASE ENTER All ","Error", JOptionPane.ERROR_MESSAGE);
if (st.searchStaffidonth(idserch.getText(), String.valueOf(m))){
            st.staffReportConditionidMonth(jTable1, idserch.getText(),String.valueOf(m));
return;}
else {
    JOptionPane.showMessageDialog(null, "NOT FOUND","STAFF",JOptionPane.INFORMATION_MESSAGE);
 return;
}
          }
        
        if (idserch.getText()!=""&&namesearch.getText().equals("")&&monthse.equals(" ")&&year!=" "){
//              JOptionPane.showMessageDialog( this, "PLEASE ENTER All ","Error", JOptionPane.ERROR_MESSAGE);
if (st.searchStaffidyear(idserch.getText(), year)){
            st.staffReportConditionidYear(jTable1, idserch.getText(),year);
return;
}
else {
    JOptionPane.showMessageDialog(null, "NOT FOUND","STAFF",JOptionPane.INFORMATION_MESSAGE);
 return;
}
          }
        
        if (idserch.getText().equals("")&&namesearch.getText()!=""&&monthse!=" "&&year.equals(" ")){
//              JOptionPane.showMessageDialog( this, "PLEASE ENTER All ","Error", JOptionPane.ERROR_MESSAGE);
        if (st.searchStaffnamemonth(namesearch.getText(), String.valueOf(m))){
            st.staffReportConditionNameMonth(jTable1, namesearch.getText(),String.valueOf(m));
return;}
        else {
            JOptionPane.showMessageDialog(null, "NOT FOUND  ","STAFF",JOptionPane.INFORMATION_MESSAGE);
 return;
        }
          }
        
        if (idserch.getText().equals("")&&namesearch.getText()!=""&&monthse.equals(" ")&&year!=" "){
//              JOptionPane.showMessageDialog( this, "PLEASE ENTER All ","Error", JOptionPane.ERROR_MESSAGE);
if (st.searchStaffnameyear(namesearch.getText(), year)){
            st.staffReportConditionNameYear(jTable1, namesearch.getText(),year);
return;}
else {
    JOptionPane.showMessageDialog(null, "NOT FOUND ","STAFF",JOptionPane.INFORMATION_MESSAGE);
 return;
}
          }
        
        if (idserch.getText().equals("")&&namesearch.getText().equals("")&&monthse!=" "&&year!=" "){
            System.out.println("hy");
if (st.searchStaffmonthyear(String.valueOf(m), year)){           
    System.out.println("9809798647836874");
st.staffReportConditionMonthYear(jTable1, String.valueOf(m), year);//Year(jTable1, namesearch.getText(),year);
return;}
else {
    JOptionPane.showMessageDialog(null, "NOT FOUND ","STAFF",JOptionPane.INFORMATION_MESSAGE);
 return;
}
          }
        
        if (idserch.getText()!=""&&namesearch.getText()!=""&&monthse!=" "&&year.equals(" ")){
//              JOptionPane.showMessageDialog( this, "PLEASE ENTER All ","Error", JOptionPane.ERROR_MESSAGE);
if (st.searchStafffidnamemonth(idserch.getText(), namesearch.getText(), String.valueOf(m))){
            st.staffReportConditionidNameMonth(jTable1, idserch.getText(),namesearch.getText(),String.valueOf(m));
return;}else {
    JOptionPane.showMessageDialog(null, "NOT FOUND ","STAFF",JOptionPane.INFORMATION_MESSAGE);
 return;
}
          }
        
        if (idserch.getText()!=""&&namesearch.getText()!=""&&monthse.equals(" ")&&year!=" "){
//              JOptionPane.showMessageDialog( this, "PLEASE ENTER All ","Error", JOptionPane.ERROR_MESSAGE);
if (st.searchStaffidmonthyear(idserch.getText(), String.valueOf(m), year)){
            st.staffReportConditionIdMonthYear(jTable1, idserch.getText(),String.valueOf(m),year);
return;}else {
    JOptionPane.showMessageDialog(null, "NOT FOUND ","STAFF",JOptionPane.INFORMATION_MESSAGE);
 return;
}
          }
        
        if (idserch.getText().equals("")&&namesearch.getText()!=""&&monthse!=" "&&year!=" "){
//              JOptionPane.showMessageDialog( this, "PLEASE ENTER All ","Error", JOptionPane.ERROR_MESSAGE);
if (st.searchStaffnamemonthyear(namesearch.getText(), String.valueOf(m), year)){
            st.staffReportConditionNameMonthYear(jTable1, namesearch.getText(),String.valueOf(m),year);
return;
}else {
    JOptionPane.showMessageDialog(null, "NOT FOUND ","STAFF",JOptionPane.INFORMATION_MESSAGE);
 return;
}
          }
        
//        if (idserch.getText()!="" && namesearch.getText()!="" && monthse!=" " && year!=" "){
////              JOptionPane.showMessageDialog( this, "PLEASE ENTER All ","Error", JOptionPane.ERROR_MESSAGE);
//            if (st.searchStaffAll(idserch.getText(), namesearch.getText(), String.valueOf(m), year)){
//       st.staffReportConditionAll(jTable1, idserch.getText(), namesearch.getText(), String.valueOf(m), year);
//   
//return;}
//            else {
//                JOptionPane.showMessageDialog(null, "NOT FOUND id name month year","STAFF",JOptionPane.INFORMATION_MESSAGE);
// return;
//            }
//          }
    }//GEN-LAST:event_addbtnMouseClicked

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
       if (id.getText().equals("")){
           JOptionPane.showMessageDialog( this, "PLEASE ENTER ID ","Error", JOptionPane.ERROR_MESSAGE);
          return;
       }
       if (name.getText().equals("")){
           JOptionPane.showMessageDialog( this, "PLEASE ENTER NAME","Error", JOptionPane.ERROR_MESSAGE);
          return;
       }
       if (present.getText().equals("")){
           JOptionPane.showMessageDialog( this, "PLEASE TYPE ANY IN PRESENT","Error", JOptionPane.ERROR_MESSAGE);
          return;
       }if (absent.getText().equals("")){
           JOptionPane.showMessageDialog( this, "PLEASE TYPE ANY IN ABSENT","Error", JOptionPane.ERROR_MESSAGE);
          return;
       }
       if (late.getText().equals("")){
           JOptionPane.showMessageDialog( this, "PLEASE TYPE ANY IN LATE","Error", JOptionPane.ERROR_MESSAGE);
          return;
       }
       Staff stf=new Staff();
       stf.updateReport(id.getText(), name.getText(), present.getText(), absent.getText(), late.getText());
       stf.staffReport(jTable1);
       name.setText("");
       present.setText("");
       absent.setText("");
       late.setText("");
       id.setText("");
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        printComponenet(printPanel);

    }//GEN-LAST:event_jPanel5MouseClicked

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed

        //classes.ClassesRecord(jTable1);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MousePressed

    private void jPanel5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseReleased
        // TODO add your handling code here:
        //classes.ClassesRecord(jTable1);
    }//GEN-LAST:event_jPanel5MouseReleased

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        printComponenet(PRINTPAnelTAble);
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MousePressed

    private void jPanel6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseReleased

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void idserchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idserchActionPerformed
        // TODO add your handling code here:
//       Student std=new Student();
//        boolean isIntegerid=std.isInteger(idserch.getText());
//          String monthse=(String)this.monthsea.getSelectedItem();
//          String year=(String)this.yearsearch.getSelectedItem();
//        if (idserch.getText().equals("")){
//           JOptionPane.showMessageDialog( this, "PLEASE ENTER ID FOR SEARCH","Error", JOptionPane.ERROR_MESSAGE);
//          return;
//       }
//       if (isIntegerid==false){
//           JOptionPane.showMessageDialog( this, "YOU ENTERED ID NUMBER IN ALPHABET ","Error", JOptionPane.ERROR_MESSAGE);
//        return;
//       }
//       Staff st=new Staff();
//       st.staffReportCondition(jTable1, idserch.getText(), namesearch.getText(), monthse, year);
    }//GEN-LAST:event_idserchActionPerformed

    private void namesearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namesearchActionPerformed
        // TODO add your handling code here:
//        Student std=new Student();
////        boolean isIntegerid=std.isInteger(namesearch.getText());
//          String monthse=(String)this.monthsea.getSelectedItem();
//          String year=(String)this.yearsearch.getSelectedItem();
//        if (namesearch.getText().equals("")){
//           JOptionPane.showMessageDialog( this, "PLEASE ENTER NAME FOR SEARCH","Error", JOptionPane.ERROR_MESSAGE);
//          return;
//       }
//       
//       Staff st=new Staff();
//       st.staffReportCondition(jTable1, idserch.getText(), namesearch.getText(), monthse, year);
//       st.sta
    }//GEN-LAST:event_namesearchActionPerformed

    private void presentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_presentActionPerformed

    private void idserchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idserchKeyTyped
        // TODO add your handling code here:
       Staff stf=new Staff();
        if (idserch.getText().equals("")){
            stf.staffReport(jTable1);
        }
    }//GEN-LAST:event_idserchKeyTyped

    private void namesearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namesearchKeyTyped
        // TODO add your handling code here:Staff stf=new Staff();
       Staff stf=new Staff();
        if (namesearch.getText().equals("")){
            stf.staffReport(jTable1);
        }
    }//GEN-LAST:event_namesearchKeyTyped

    private void monthseaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthseaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_monthseaActionPerformed

    private void yearsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearsearchActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        try{
            int row= jTable1.getSelectedRow();
            String idcl= jTable1.getModel().getValueAt(row, 0).toString();
//            String sql= "select * from Student where IDnum = '" + table_click + "'";
//            pst=con.prepareStatement(sql);
//            rs=  pst.executeQuery();
String namecl= jTable1.getModel().getValueAt(row, 1).toString();
String pre= jTable1.getModel().getValueAt(row, 2).toString();
String abs= jTable1.getModel().getValueAt(row, 3).toString();
String lat= jTable1.getModel().getValueAt(row, 5).toString();
            id.setText(idcl);
            name.setText(namecl);
            present.setText(pre);
            absent.setText(abs);
            late.setText(lat);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PRINTPAnelTAble;
    private javax.swing.JTextField absent;
    private javax.swing.JPanel addbtn;
    private javax.swing.JTextField id;
    private javax.swing.JTextField idserch;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator33;
    private javax.swing.JSeparator jSeparator34;
    private javax.swing.JTable jTable1;
    private javax.swing.JFormattedTextField late;
    private javax.swing.JComboBox<String> monthsea;
    private javax.swing.JTextField name;
    private javax.swing.JTextField namesearch;
    private javax.swing.JTextField present;
    private javax.swing.JPanel printPanel;
    private javax.swing.JComboBox<String> yearsearch;
    // End of variables declaration//GEN-END:variables
}
