/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import javax.swing.JPanel;
import code.Staff;
import code.Finance;
/**
 *
 * @author Mithrandir
 */
public class statisticsPanel extends javax.swing.JPanel {

    /**
     * Creates new form statisticsPanel
     */JPanel childPanel;
     int m;
     Staff staff=new Staff();
     Finance finance=new Finance();
    public statisticsPanel() {
        initComponents();
        exlabl.setVisible(false);
        salaryduelabl.setVisible(false);
        salarylabl.setVisible(false);
        int a=staff.getYear();
        Object z=a;
        yearsearch.setSelectedItem(z.toString());
        String monthse=(String)this.monthsea.getSelectedItem();
        String year=(String)this.yearsearch.getSelectedItem();
        int y=Integer.parseInt(year);
        m=staff.getMonthInt(m,monthse);
        finance.totalamount(m, y, incomeJlbl, exlabl, feeslabl, feeduelabl, salarylabl, salaryduelabl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        incomeJlbl = new javax.swing.JLabel();
        exlabl = new javax.swing.JLabel();
        monthsea = new javax.swing.JComboBox<>();
        yearsearch = new javax.swing.JComboBox<>();
        addbtn4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        salarylabl = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        feeslabl = new javax.swing.JLabel();
        salaryduelabl = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        feeduelabl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1163, 750));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/icons8-back-48.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setText("STATISTICS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel4.setText("TOTAL INCOME");

        incomeJlbl.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        incomeJlbl.setText("TOTAL AMOUNT OF INCOME");

        exlabl.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        exlabl.setText("TOTAL AMOUNT OF INCOME");

        monthsea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "JANUARY", "FEBUARY", "MARCH", "APRIL", "MAY", "JUNE", "JULY", "AUGUST", "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER" }));
        monthsea.setSelectedIndex((staff.getMonth()));
        monthsea.setSelectedItem((staff.getYear()));
        monthsea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthseaActionPerformed(evt);
            }
        });

        yearsearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1982", "1981", "1980" }));
        yearsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearsearchActionPerformed(evt);
            }
        });

        addbtn4.setBackground(new java.awt.Color(51, 153, 255));
        addbtn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addbtn4addbtn2MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/icons8-search-40.png"))); // NOI18N
        jLabel8.setText("SEARCH");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout addbtn4Layout = new javax.swing.GroupLayout(addbtn4);
        addbtn4.setLayout(addbtn4Layout);
        addbtn4Layout.setHorizontalGroup(
            addbtn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addbtn4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel8)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        addbtn4Layout.setVerticalGroup(
            addbtn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addbtn4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel6.setText("MONTH");

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel7.setText("YEAR");

        salarylabl.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        salarylabl.setText("TOTAL AMOUNT OF INCOME");

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel10.setText("TOTAL FEES");

        feeslabl.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        feeslabl.setText("TOTAL AMOUNT OF INCOME");

        salaryduelabl.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        salaryduelabl.setText("TOTAL AMOUNT OF INCOME");

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel12.setText("TOTAL FEES DUES");

        feeduelabl.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        feeduelabl.setText("TOTAL AMOUNT OF INCOME");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(282, 282, 282))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(feeduelabl, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(feeslabl, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(incomeJlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(monthsea, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                                .addComponent(yearsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(217, 217, 217)))
                .addComponent(addbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exlabl, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salarylabl, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(salaryduelabl, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(incomeJlbl)
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(yearsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(monthsea, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(152, 152, 152)
                        .addComponent(exlabl)
                        .addGap(74, 74, 74)))
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(feeslabl)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel12)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(salarylabl)
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salaryduelabl)
                            .addComponent(feeduelabl))))
                .addContainerGap(146, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        childPanel=new adminFinance();
        childPanel.setSize(this.getSize());
        this.removeAll();
        this.repaint();
        this.add(childPanel);
        this.validate();
    }//GEN-LAST:event_jPanel1MouseClicked

    private void monthseaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthseaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthseaActionPerformed

    private void yearsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearsearchActionPerformed

    private void jLabel8jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8jLabel6MouseClicked
        // TODO add your handling code here:
        String monthse=(String)this.monthsea.getSelectedItem();
        String year=(String)this.yearsearch.getSelectedItem();
 int y=Integer.parseInt(year);
        m=staff.getMonthInt(m,monthse);
        finance.totalamount(m, y, incomeJlbl, exlabl, feeslabl, feeduelabl, salarylabl, salaryduelabl);
        
    }//GEN-LAST:event_jLabel8jLabel6MouseClicked

    private void addbtn4addbtn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbtn4addbtn2MouseClicked

        //         StudentFeesChallan std=new StudentFeesChallan();
        //        boolean isIntegerid=std.isInteger(idserch.getText());
         String monthse=(String)this.monthsea.getSelectedItem();
        String year=(String)this.yearsearch.getSelectedItem();
        int y=Integer.parseInt(year);
        m=staff.getMonthInt(m,monthse);
        finance.totalamount(m, y, incomeJlbl, exlabl, feeslabl, feeduelabl, salarylabl, salaryduelabl);
    }//GEN-LAST:event_addbtn4addbtn2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addbtn4;
    private javax.swing.JLabel exlabl;
    private javax.swing.JLabel feeduelabl;
    private javax.swing.JLabel feeslabl;
    private javax.swing.JLabel incomeJlbl;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> monthsea;
    private javax.swing.JLabel salaryduelabl;
    private javax.swing.JLabel salarylabl;
    private javax.swing.JComboBox<String> yearsearch;
    // End of variables declaration//GEN-END:variables
}
